### PR TITLE
filtering clients at create guarantor

### PR DESCRIPTION
**Pull request by francisguchie**
## Description
https://github.com/openMF/community-app/issues/3253

## Related issues and discussion
https://github.com/openMF/community-app/issues/3253

## Screenshots, if any
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Review by awasum — APPROVED** [review]
LGTM. @santoshconflux , @edcable , @vorburger , @francisguchie, do you have someone who can actually functionally review this and merge?

**Comment by vorburger** [comment]
@awasum I unfortunately won't be able to engage on helping to review PRs on openMF/community-app (just time wise).

**Comment by edcable** [comment]
@bharathcgowda Could you do a functional review/test of this?

**Review by bharathcgowda — APPROVED** [review]
Functionally this enhancement is good and sorts out the client listing problem with office and set of words filters in place.

**Pull request merged**
