### PR TITLE
Fix #2041 Dashboard Charts and Panel Headers

### LINKED ISSUE #2041: Dashboard is not showing the charts
Screenshot from reskin(https://demo.openmf.org/newbeta/#/richdashboard):

reskin

Screenshot without reskin(https://demo.openmf.org/#/richdashboard)

demo

### PR DESCRIPTION
**Pull request by abhaychawla**
## Description
The dashboard was not showing the charts as the angularjs-nvd3-directives for creation and display of charts have a dependency on the packages d3 version 3.3.13 and nvd3 version 1.1.15-beta as specified here https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/blob/master/bower.json. The bower.json file in the community-app referenced higher versions (d3: 3.5.12, nvd3: 1.8.3) which have been significantly updated and thus were giving an error in the console (nv.models.pieChart(...).x(...).y(...).width(...).height(...).tooltips is not a function) and not displaying the charts.
Thus, the bower.json file was updated with the required versions.
The UI for panel headings was corrected as it wasn't being displayed properly.
By default, the chart for the first office in dropdown menu is being displayed so corresponding models were updated with id=1 to signify the same.

## Related issues and discussion
#2041 

## Screenshots, if any
Before:
screenshot 252
screenshot 253

After:
screenshot 250
screenshot 251

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@abhaychawla I pulled this locally and did an `npm install` and `bower install`, 

which gave me this error:
error

Due to which the community-app isn't loading properly, am I missing something?

**Comment by abhaychawla** [comment]
Did you get an option like this after this conflict error:
1) d3#3.3.13 which resolved to 3.3.13 and is required by community-app
2) d3#~3.3.13 which resolved to 3.3.13 and is required by nvd3#1.1.15-beta
3) d3#^3.4.4 which resolved to 3.5.17 and is required by nvd3#1.8.3

and were able to install the required dependencies (2) as changed in bower.json?

If not, try uninstalling the packages d3 and nvd3 and then do a bower install for these packages. This should fix it. 

The charts do not work with newer versions of these packages as they aren't compatible with each other due to some code changes.
If the problem still persists let me know.

**Comment by chandaaparna** [comment]
We have done bower install for installing old versions of nvd3, d3 and was able to see the charts on dashboard but the issue is we were not able to see the tooltips for pie chart. We were able to see tooltips for bar charts but the alignment of tooltip is not proper as shown in the screenshot 
image

Could you please help us in resolving the tooltip issue for pie chart and tooltip proper alignment for bar chart.

**Comment by chandaaparna** [comment]
@gkrishnan724;@abhaychawla;@mbj36 : Could any of you please help in resolving the tooltip issue in Dashboard.

**Comment by abhaychawla** [comment]
Yes @chandaaparna, sorry for late reply we will try to fix this as soon as possible.

**Pull request merged**
