### PR TITLE
Reskin: Fix issue #1969 -  No exception thrown during "loan product" creation

### PR DESCRIPTION
**Pull request by Anh3h**

### CODE REVIEW

**Comment by Anh3h** [comment]
Added red asterisk for required fields. Hope that is okay :)

**Comment by Anh3h** [comment]
Earlier UI:
c1

Updated UI:
p1
p2

**Comment by Anh3h** [comment]
Affected view: https://demo.openmf.org#/createloanproduct

**Comment by mbj36** [comment]
Thanks @Anh3h This solves some major issues :)

**Pull request merged**
