### PR TITLE
FINERACT-1374-Withdraw-Charge-Discount-WIth-PaymentTypes

### PR DESCRIPTION
**Pull request by rrpawar96**
## Related issues and discussion
https://issues.apache.org/jira/browse/FINERACT-1374

https://issues.apache.org/jira/browse/FINERACT-1390

### CODE REVIEW

**Comment by rrpawar96** [comment]
@awasum @avikganguly01 Please review and merge this PR as well, This feature has been tested by @francisguchie

**Comment by francisguchie** [comment]
@bharathcgowda @awasum 

Like i said on the Fineract i already tested this functionality and put it in a "live" production to confirm its

**Comment by awasum** [comment]
Fineract PR: https://github.com/apache/fineract/pull/1969

**Review by awasum — APPROVED** [review]
LGTM

**Pull request merged**
