### PR TITLE
fix #2729-Edit buttons not aligned properly

### LINKED ISSUE #2729: Edit buttons not aligned properly
## Description
Edit buttons not aligned properly throughout the webpage

## Steps to Reproduce
Admin->product->Loan Products

## Expected Behaviour
proper padding required

## Actual Behaviour
not aligned

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
screenshot from 2018-01-05 16 14 07

### PR DESCRIPTION
**Pull request by muddlebee**
## Description
Edit button alligned properly by introducing padding

## Related issues and discussion
#2729 

## Screenshots, if any
screenshot from 2018-01-05 16 18 52

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Review by gkrishnan724 — CHANGES_REQUESTED** [review]
@anweshknayak Please make the css changes in the sass file and then compile it using the sass command

**Comment by anweshknayak** [comment]
@gkrishnan724 necessary to make changes in sass? I thought css compiles to sass here. Or maybe I missed something?

**Comment by gkrishnan724** [comment]
@anweshknayak Sass is used for generating and coding css easily. https://sass-lang.com/guide

**Comment by anweshknayak** [comment]
Thanks will make the changes asap

**Pull request closed without merging**
