### PR TITLE
Not able to create the client address due to missing street field in UI

### PR DESCRIPTION
**Pull request by habile-technologies**
#3249

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
https://github.com/openMF/community-app/pull/3344

**Comment by BLasan** [comment]
@bharathcgowda Address creation part is alright. But there's an issue in editing that and adding a new address inside the client's page.
Screenshot from 2021-05-18 22-04-13

**Comment by bharathcgowda** [comment]
@habile-technologies  Can you please look into the edit portion as well?

**Comment by bharathcgowda** [comment]
@BLasan  can you please help in reviewing this too?

**Review by BLasan — APPROVED** [review]
LGTM!

**Comment by bharathcgowda** [comment]
Hi Ramesh/ Charulatha, address addition to the client is working from the client view page, however, it is not working from "create client screen".

State and country dropdown are not getting values, because of which the client creation is not happening, could you please check again

To reproduce.
Create a client, add address while creating client as shown in the screenshot.

image

**Pull request merged**
