### PR TITLE
Fixed issue #1901

### PR DESCRIPTION
**Pull request by Anh3h**

### CODE REVIEW

**Comment by mbj36** [comment]
@Anh3h this issue belongs to new_reskin branch, but you have created a PR in develop branch. Closing the PR

**Comment by Anh3h** [comment]
ok will send the request to that branch

**Comment by mbj36** [comment]
You should checkout new_reskin branch

**Comment by Anh3h** [comment]
I should checkout new_reskin branch as in in should fix the issue on new_reskin branch ?

**Comment by mbj36** [comment]
Yes this issue exist in new_reskin branch, let me know if u have any problem in checking out new_reskin branch. You can find demo server here - https://demo.openmf.org/newbeta

**Comment by Anh3h** [comment]
ok thanks

**Pull request closed without merging**
