### PR TITLE
Mifosx 2167

### PR DESCRIPTION
**Pull request by dilankamr**
Hi All,

I fixed the issue ['MIFOSX-2167' (Not able to select the role in edit user page)](https://mifosforge.jira.com/browse/MIFOSX-2167) and this is the PR for the new changes. 
Please be kind enough to review this code inform me whether it is correct or not.

Thanks,
Dilanka Rathnayake.

### CODE REVIEW

**Comment by mbj36** [comment]
@dilankamr I would suggest you to squash your commits :)

**Comment by UltimateSupreme** [comment]
Also, I think you need to remove all those `console.log`s from your code

**Comment by dilankamr** [comment]
Hi @mbj36, @UltimateSupreme, 

Sorry for the mistakes. I ll fix them in my codes.

Thanks All,
Dilanka Rathnayake.

**Comment by rajuan** [comment]
Please resend PR with single commit and only relevant changes

**Pull request closed without merging**
