### PR TITLE
Fixed #2893

### LINKED ISSUE #2893: Missing validation when restricted dates are entered (Parent issue #2859)
## Description
In the "Joined on" section which is mandatory to be filled while creating an employee, restricted dates are disabled on the calendar which pops up but can be manually typed and are successfully validated.

## Steps to Reproduce
Mifos Menu Bar >> Admin >> Organization >> Manage Employees >> Create Employee >> Enter all the required fields >> In the joining date, enter a restricted date manually (e.g.: "20 December 2060") >> Submit
or
Mifos Menu Bar >> Admin >> Organization >> Manage Offices >> Create Office >> Enter all the required fields >> In the "Opened on" field, enter a restricted date manually (e.g.: "20 December 2060") >> Submit

## Expected Behaviour
An error message should appear saying "Invalid date entered"

## Actual Behaviour
The employee is created successfully.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox, Google Chrome

## Screenshots, if any
image
image
image

### PR DESCRIPTION
**Pull request by sarthak-sehgal**
## Description
Appropriate validation has been added to dates in "Create office" and "Create employee." Future dates are not acceptable now in "Create office" and future/past dates (dates before opening of the particular office) are not acceptable now in "Create employee."

## Related issues and discussion
#2893

## Screenshots, if any
2893fix_1
2893fix_2

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by sarthak-sehgal** [comment]
@mbj36, @gkrishnan724 Please review.
Also, should "Edit office" and/or "Edit employee" contain any restriction for the date? I think that the app should not allow any future date to be entered in both. What are your thoughts on this?

**Comment by shrunk3** [comment]
@sarthak-sehgal i recommend this to be of type date picker and and dont allow the user to select the future dates, please make the required changes and resend the PR. we will wait for a weeek if we dont receive the PR we will close this PR.

**Comment by sarthak-sehgal** [comment]
Hi, thanks for your comment. Unfortunately I am no longer in the capacity to work on this PR. Closing it.

**Pull request closed without merging**
