### PR TITLE
Reskin: Fix #2040 - Icons not displaying on localhost

### LINKED ISSUE #2040: Reskin:Create Client page is not showing '+' button or 'x' button in address module
Go to System > Configurations and search for 'Enable-Address' and enable it.
Go to clients and click on '+Create Client' to Create client page:
reskin

Without reskin:

demo

### PR DESCRIPTION
**Pull request by gkrishnan724**

### CODE REVIEW

**Comment by gkrishnan724** [comment]
@mbj36 This was an angular-wizard problem https://github.com/angular-wizard/angular-wizard/issues/79
the wizard title is shown on hover everywhere. I made the changes, hope its fixed :)

**Comment by gkrishnan724** [comment]
@mbj36 I don't know what you are talking about, I just checked it. Its fixed. look at the screenshot below:
screenshot from 2017-03-10 10-53-54

I did a `git commit --amend`  maybe you didn't notice that I have changed `title` to `data-title`. did you pull my changes locally ?. I even verified by pulling my PR locally. sorry If i did something wrong.

**Comment by mbj36** [comment]
Let me have a double check on it :)

**Comment by mbj36** [comment]
Let me have a double check on it

On 10 Mar 2017 11:00 am, "GopalaKrishnan P" <notifications@github.com>
wrote:

@mbj36 <https://github.com/mbj36> I don't know what you are talking about,
I just checked it. Its fixed. look at the screenshot below:
[image: screenshot from 2017-03-10 10-53-54]
<https://cloud.githubusercontent.com/assets/21004514/23783233/0b475b52-0580-11e7-81a0-1d56d2b9f1b9.png>

I did a git commit --amend maybe you didn't notice that I have changed title
to data-title. did you pull my changes locally ?. I even verified by
pulling my PR locally. sorry If i did something wrong.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openMF/community-app/pull/2068#issuecomment-285582159>,
or mute the thread

**Pull request merged**
