### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by awasum**

### CODE REVIEW

**Comment by awasum** [comment]
This is better... 
But PhantomJS2 still fails under travis to when running `npm test`

**Comment by awasum** [comment]
@vorburger , @ShruthiRajaram  Just used trial and error to get this working over many trials.

Sorry, Am not very good with Nodejs or Javascript

Dont merge, I will close this and create a clean PR with just one commit which works.

**Comment by awasum** [comment]
See : https://askubuntu.com/questions/722075/no-installation-candidate-for-libicu52-on-15-10
https://gist.github.com/telbiyski/ec56a92d7114b8631c906c18064ce620

**Comment by awasum** [comment]
See this new clean PR: https://github.com/openMF/community-app/pull/3116

**Comment by vorburger** [comment]
> Dont merge, I will close this and create a clean PR with just one commit which works.
> See this new clean PR: #3116

try `git rebase -i develop` - it's cool, and useful, for this kind of thing.

**Comment by awasum** [comment]
> > Dont merge, I will close this and create a clean PR with just one commit which works.
> > See this new clean PR: #3116
> 
> try `git rebase -i develop` - it's cool, and useful, for this kind of thing.

Thanks..I will try this for learning purpose and use it next time.

**Pull request closed without merging**
