### PR TITLE
Fix #2952 - Fixes ability to uncheck 'all function' checkbox

### LINKED ISSUE #2952: Admin can uncheck "ALL FUNCTION" permission checkbox which removes the admin privilages
## Description
Admin user is allowed to uncheck "ALL FUNCTION" permission on Permissions:  Special screen. It drops the admin privileges for all the other admin user as well.
 Is there any way by which we can get the admin privileges back.

## Steps to Reproduce
Login to community app as admin. 
Navigate to Admin>>System>>Manage Roles And Permissions and select an admin user. Then on Permission:Special edit screen, uncheck "ALL FUNCTION" checkbox and check "ALL FUNCTION READ" checkbox and save.  Now the admin role has only read privileges.
 
## Expected Behaviour
"ALL FUNCTION" checkbox should not be editable, as it drops all admin privileges. 

## Actual Behaviour
After unchecking the "ALL FUNCTION" checkbox, admin user does not have write privileges. 

## Settings
- Mifos X version: 17.07.01
- Browser used: Chrome

### PR DESCRIPTION
**Pull request by OHassini**
## Description
Made the "ALL FUNCTION" permission checkbox not editable.

 ## Related issues and discussion
#2952 

## Screenshots, if any
Before:
Capture d’écran (203)

After:
Capture d’écran (200)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by OHassini** [comment]
@luckyman20 @abhaychawla please have a look !!

**Review by abhaychawla — CHANGES_REQUESTED** [review]
@OussEmaDevCode Only the users with `admin` roles, should not be allowed to update/uncheck `All Functions` checkbox if its already checked in `admin` roles according to the description of the issue. Please reiterate over your solution as it won't work as expected.

**Comment by OussEmaDevCode** [comment]
@abhaychawla Done !!!

**Comment by OHassini** [comment]
@abhaychawla Done !!! please have a look.

**Review by abhaychawla — CHANGES_REQUESTED** [review]
@OussEmaDevCode The current logic causes the first checkbox of each group to be disabled if its checked. Also, the checkboxes should be editable only in case of Edit Role but it they have now become editable in View Role as well. You can check and try to resolve.

If the issue seems to be a bit complicated, we can try a workaround. You may not change the current logic, but try to show an alert to the user when All Functions checkbox is unchecked to confirm if he wants to change by it notifying him that it will affect all the users associated to this role and uncheck once he presses ok, if he presses cancel keep it as it is.

If the alternate solution seems better to you you may try and implement that.

**Comment by OussEmaDevCode** [comment]
@abhaychawla The problem was fixed and sorry for the delay

**Comment by OHassini** [comment]
@abhaychawla I kept working on the first solution, the problem was fixed and sorry for the delay

**Comment by OussEmaDevCode** [comment]
@abhaychawla please have a look !!

**Comment by OussEmaDevCode** [comment]
@abhaychawla please have a look !!

**Comment by OHassini** [comment]
@abhaychawla please have a look !!

**Comment by abhaychawla** [comment]
@OussEmaDevCode As I mentioned before, the first checkbox of each group becomes disabled if its checked. Only the `All Functions` checkbox should be disabled provided its already checked and only in case when a user with `Admin` role tries to edit. Also, even while editing if it was not checked before and checked now it should not imediatelly get disabled until the user submits. 

Also, I would request you not to tag me again and again in the PR. The mentors are allowed some time for review. Commenting multiple times like this doesn't help to get it faster. I understand that this has been a tough issue to work with.

**Comment by OHassini** [comment]
@abhaychawla Hi, first of all thank you for your understanding and sorry for disturbing you, this commit should be good to go, as you said now only the "all Functions" checkbox is disabled if it's already checked and if the user has an admin role (which he has to have in order to edit the "all Functions checkbox") and now the checkbox doesn't get imediatelly disabled (the user has to click submit in order for it to get disabled).

**Review by abhaychawla — APPROVED** [review]
Its working well, Good!!

**Pull request merged**
