### PR TITLE
Getting-Started.md

### PR DESCRIPTION
**Pull request by SupreethSudhakaranMenon**
## Description
This is a Getting Started File for the people who are visiting the Github repository page of the app for the first time and I have made corrections to the file which will also help people to get their first steps of the contribution right.

## Related issues and discussion
3097

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by awasum** [comment]
This solves #3098  @santoshconflux

**Comment by santoshconflux** [comment]
@awasum , could you review and merge it?

**Comment by awasum** [comment]
It looks good to me @santoshconflux and I dont have permission to merge on this repo.

**Comment by vorburger** [comment]
> I dont have permission to merge on this repo.

sounds like to me that you definitely should be able to... :globe_with_meridians: 

So I just invited you, you should have received an email from GitHub, to accept? 

Test if you can merge this? PS: I think this should be linked from the README... will you add that?

**Comment by awasum** [comment]
Thanks @vorburger , can merge now. I will merge this and link the Getting start from README in another PR.

**Comment by awasum** [comment]
See this as a follow up: #3113 

Thanks @SupreethSudhakaranMenon

**Pull request merged**
