### PR TITLE
Fixes #2934: Logo Not Updated

### LINKED ISSUE #2934: Logo is not getting updating even the logo is changed in logo.json file
In login page  , the logo next to MifosX (check the screenshot) is not getting updated even the logo is changed in logo.json file.

screenshot from 2018-04-05 11-22-53

### PR DESCRIPTION
**Pull request by jonathanzhang53**
Fixes #2934 

## Description:
Changed the occurences of mifos-flat-logo.png (OLD LOGO) to mifos_lg-logo.jpg (NEW LOGO). 

#### New Login:
image
#### New NavBar:
image

## Checklist:
- [] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code. **`Got network error: revalidating... Skipping to Next File` for all files**
[This may shed some light on the issue.](https://github.com/praveenvijayan/grunt-html-validation/issues/78)

- [] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything. **Showed up as a blank page for me?**

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by bauripalash** [comment]
I don't think the issue is actually getting solved , because if you read the description carefully, it says:
> In login page , the logo next to MifosX (check the screenshot) is not getting updated *even the logo is changed in logo.json file.*

Actually the issue is kind of confusing , according to it there should be a `logo.json` file but there's not, instead there's a file `app/scripts/config/LogoConfig.json` which is empty. 

Then how we're supposed to update logo configuration😓

**Comment by jonathanzhang53** [comment]
@bauripalash If you look at the issue, abiyats says how it should be fixed. The logo.json file does not exist. I think the issue was misnamed.

**Comment by bauripalash** [comment]
Actually The **Issue has some Issues**

**Comment by jonathanzhang53** [comment]
@bauripalash LOL i actually laughed.

**Comment by ShruthiRajaram** [comment]
@bauripalash I agree with you on "Issue has some Issues" . And @jonathanzhang53 I agree to your point that you followed solution proposed by abiyats. I have requested for clarification on the issue, lets wait.

**Comment by edcable** [comment]
Closing as issue is invalid.

**Pull request closed without merging**
