### PR TITLE
FINEACT-130:HoldAccount

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by rrpawar96** [comment]
**Blocking Debit/Credit:**
image
image
image
image

**Blocking Amount Transaction:** 
transaction_hold
image



**Releasing (Blocked) Amount:** 
releaseamount-130

**Comment by ikimbra** [comment]
Wow, thanks a lot @rrpawar96 this is a great initiative of making Mifos yet a robust function-rich application. I had issues with our clients here who have savings products with loans where most of these scenarios happen. @francisguchie please test this out before we plan ahead putting it into production if approved.

**Comment by er-prince** [comment]
@rrpawar96  testing ...

**Comment by rrpawar96** [comment]
Hi, @luckyman20 The backend of this PR is got merged, Please review this PR

**Comment by er-prince** [comment]
@rrpawar96  Tested it .. Working Fine

**Comment by francisguchie** [comment]
> @rrpawar96 Tested it .. Working Fine

@er-prince  thanks for testing - I tested too and was fine been waiting for another person so i can add my +1 on it.

**Review by luckyman20 — APPROVED** [review]
Looks good to me!

**Comment by rrpawar96** [comment]
Thanks, @luckyman20 for the review. @bharathcgowda  @awasum  Please merge this PR.

**Comment by v3ss0n** [comment]
How to unfreeze saving?

**Comment by francisguchie** [comment]
@v3ss0n ,
there are different forms of freezing read more [FINERACT-130 ](https://issues.apache.org/jira/browse/FINERACT-130). 
in a nut shell, freeze, hold an amount, credit freeze and debit freeze. 

where an account is frozen, a user will just un-freeze the undo of freezing 
where an account is on hold by an Amount, a user will un-hold the amount that has been held so the client can withdraw it

I hope this helps

**Pull request merged**
