### PR TITLE
Editting Employee mobile Number for SMS Should only allow numeric

### LINKED ISSUE #2962: Employee- Mobile Number for SMS Should only allow numeric
**Steps to Produce**
Create/Edit Employee, Fill Mobile Number for SMS with any characters > Submit
employee2018-05-22 13-42-34
.
**Expected Behavior**
Should behave like client mobile number field
client 2018-05-22 13-38-19
For Numeric(Special Character) examples visit https://github.com/openMF/community-app/issues/679 ,

### PR DESCRIPTION
**Pull request by elirehema**
## Description
 Mobile Number for SMS field in Editting Employee allow user to enter text while it  Should only allow numeric and show error otherwise, as exmplained in issues #2962

## Related issues and discussion
#2962

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by ShruthiRajaram** [comment]
@elirehema thanks for the PR.  The issue says create and edit employee forms need validation. Can you put validation in Createemployee form also?

**Comment by elirehema** [comment]
@ShruthiRajaram  Read issue #2962, I can't found form validation in there. I think she mean Creating and Editing forms have phone number validation problem.

**Comment by ShruthiRajaram** [comment]
@elirehema in the issue #2962  I think @Agnessy is referring both create and edit employee pages by stating ---"Steps to Produce
Create/Edit Employee, Fill Mobile Number for SMS with any characters > Submit " . So I believe the issue will be fixed completely if same validation is added in the page "createemployee.html" for mobile number field.

**Comment by elirehema** [comment]
@ShruthiRajaram  createemployee.html phone validation Is resolve in my pull request #3034

**Comment by elirehema** [comment]
@ShruthiRajaram did you check out PR #3034 ?

**Comment by ShruthiRajaram** [comment]
@elirehema since the change is not big, I prefer single PR for the issue. @abhaychawla @gkrishnan724 if you are okay with 2 PRs for this issue, kindly approve.

**Review by wkk91193 — CHANGES_REQUESTED** [review]
@elirehema Could you create a single PR squashing changes for both edit and create screens. This is easy for later references. @edcable  What do you make of this?

**Pull request merged**
