### PR TITLE
Drop down in date fixed

### LINKED ISSUE #2649: Today's Date in drop-down calendar is not displaying properly while taking New share account application
Please check the drop-down calendar and find Today's Date.

calender menu

### PR DESCRIPTION
**Pull request by anweshknayak**
fixes #2649 

screenshot from 2017-12-12 22 06 16

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

This message was posted by [GitMate.io](https://gitmate.io) with timestamp signature `Thanks for the PR, It will be reviewed Shortly!:1eOnqh:t0P_Lq05CNmEoCHozd1zxf5xNwY`

**Comment by fazerlicourice7** [comment]
This [GCI task](https://codein.withgoogle.com/tasks/6319004404678656/?sp-organization=6239808655458304) should be closed.

**Comment by mbj36** [comment]
CC - @gkrishnan724

**Comment by mbj36** [comment]
@anweshknayak  Are you looking to address the comments ?

**Comment by anweshknayak** [comment]
@mbj36 @gkrishnan724 done. Sorry for late response.

**Pull request merged**
