### PR TITLE
Unable to Create Fixed Deposit and Recurring Deposit Products #3312

### PR DESCRIPTION
**Pull request by habile-technologies**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@bharathcgowda Able to create FD and Recurring Deposit Product successfully
Note: Created with the required data only.

**Comment by bharathcgowda** [comment]
@BLasan can we merge this  PR then?

**Comment by BLasan** [comment]
> @BLasan can we merge this PR then?

Yuh, we can merge this

**Comment by bharathcgowda** [comment]
@habile-technologies  Can you please test this fix again, We are able to get the interest-chart dropdown however, still there are issues with amount fields( I guess it could be a wrong mapping issue)

image

**Pull request merged**
