### PR TITLE
Fixed - #1773 and #1784

### PR DESCRIPTION
**Pull request by skprabhanjan**
Fixed - Bug Number #1773 (Edit Button for maker tasks goes out of border) 
Fixed - Bug Number #1784 (Create Loan Product View extends off screen)

### CODE REVIEW

**Comment by skprabhanjan** [comment]
Travis CI checks are failing and throwing an error saying "cannot start phantomJS2" and therefore the PR is failing, Any specific fix to solve this issue.?
screen shot 2017-02-03 at 10 44 01 pm

**Comment by mbj36** [comment]
Travis CI is now fixed, send PR with single commit

**Comment by skprabhanjan** [comment]
@mbj36 , Should l send a PR for both the issues #1773 and #1784 .? Or should I send a PR for single issue separately.?

**Comment by mbj36** [comment]
#1773 is open, send PR for it

**Pull request closed without merging**
