### PR TITLE
fix: Issue #2679 - Added Tooltip for Client status

### LINKED ISSUE #2679: Client Status Color Icon should display Tooltip on Hovering
## Description
For quick reference, the color icons by client name denote the status of the client. For those who don't know what status the color corresponds to, the actual status should be displayed in a tooltip when hovering over, as is the case with the color squares by the loan and savings accounts.

Navigate to any client, when placing cursor over the colored circle by client name, Tooltip should display the status

* Green - Active
* Yellow - Pending
* Black/Grey - Closed 
* Red - Transfer in Progress

You can learn more about client life cycle statuses at https://mifosforge.jira.com/wiki/spaces/docs/pages/89718816/Client+life+cycle+statuses

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #2679 

@gkrishnan724 @mbj36 @edcable @botraunak Please review it !!

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@luckyman20 could you please do the same changes in `viewclient.html` too? I forgot to mention that. There is no tooltip there too.

**Comment by luckyman20** [comment]
@gkrishnan724 I have update the PR according to the changes you requested.

**Comment by gkrishnan724** [comment]
Looks Good! thanks @luckyman20

**Pull request merged**
