### PR TITLE
FINERACT-1432:ClientDocument_DropDown

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by ikimbra** [comment]
@rrpawar96 is this done? Am interested

**Comment by rrpawar96** [comment]
> @rrpawar96 is this done? Am interested
Yes, it's done.

**Comment by rrpawar96** [comment]
let's wait until Backend : https://github.com/apache/fineract/pull/1996 to get merged

**Comment by rrpawar96** [comment]
@bharathcgowda, Please merged this PR, FINERACT PR is been merged https://github.com/apache/fineract/pull/1996

**Comment by bharathcgowda** [comment]
@luckyman20  @BLasan  can any one of you please help in the review of this PR?

**Review by luckyman20 — COMMENTED** [review]
Attach the screenshots. Else looks good.

**Comment by rrpawar96** [comment]
CustomerDoc_CodeValue

1432-ClientDropdown

documents

**Comment by rrpawar96** [comment]
thanks, @luckyman20 for reviewing.

**Pull request merged**
