### PR TITLE
fix #3327 - Unable to Edit the Shares Product

### LINKED ISSUE #3327: Unable to Edit the Shares Product
Unable to Modify the already created shares product. Submit button is not working

You can try out here:
https://openmf.github.io/community-app/?baseApiUrl=https%3A%2F%2Fdemo.fineract.dev&tenantIdentifier=default#/editshareproduct/2

issue

### PR DESCRIPTION
**Pull request by tonic889**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@tonic889 Please resolve merge conflicts

**Comment by BLasan** [comment]
@tonic889 Please follow the commands as mentioned to resolve merge conflicts and send PR containing only one commit.
 Rename the commit name to Fix #3329 - Edit Shares Product

```
git checkout community-app-3327
git remote add upstream https://github.com/openMF/community-app.git
git fetch upstream develop
git rebase upstream/develop
```

**Review by BLasan — CHANGES_REQUESTED** [review]
@tonic889 Please follow the commands as mentioned to resolve merge conflicts and send PR containing only one commit.
Rename the commit name to Fix #3329 - Edit Shares Product

```
git checkout community-app-3327
git remote add upstream https://github.com/openMF/community-app.git
git fetch upstream develop
git rebase upstream/develop
```

**Review by BLasan — APPROVED** [review]
LGMT! @spider0061 Shall we review and merge this ?

**Review by BLasan — CHANGES_REQUESTED** [review]
@tonic889 Please make the changes as required

**Comment by BLasan** [comment]
@tonic889 Add the relevant issue number in the PR description

**Comment by BLasan** [comment]
@bharathcgowda Shall we rename the commit message in a standard way and merge this?

**Comment by bharathcgowda** [comment]
Yes, we can do that to maintain consistency @BLasan

**Comment by BLasan** [comment]
> Yes, we can do that to maintain consistency @BLasan

Shall we close this PR then due to the inactivity? I'll send a PR with the requested changes and adding @tonic889 as co-author

**Comment by tonic889** [comment]
I can make the changes, just need a day or two. Thanks.

**Comment by tonic889** [comment]
These commands aren't working for and I don't know how to fix it.  This branch was current when I originally submitted my PR.  Since it seems you have already submitted another PR, perhaps it is better to use that one.

**Comment by BLasan** [comment]
> These commands aren't working for and I don't know how to fix it. This branch was current when I originally submitted my PR. Since it seems you have already submitted another PR, perhaps it is better to use that one.

I've named you as the co-author in that PR. Thanks!

**Pull request closed without merging**
