### PR TITLE
Dispay info about office in organization tree view.

### PR DESCRIPTION
**Pull request by TypicalGitHubUser**

### CODE REVIEW

**Comment by maektwain** [comment]
@mbj36 can you help me in this i dont have machine where i can check the code for next few hours if you have time . or else i will do it.

**Comment by nazeer1100126** [comment]
Please add Jira number to this PR.

**Comment by TypicalGitHubUser** [comment]
@nazeer1100126 I did not find it on JIRA. It was a Code-In task and I`m not sure this issue has own number.

**Comment by mbj36** [comment]
We are moving to new_reskin from develop branch so this PR can't be accepted as of now :)

**Pull request closed without merging**
