### PR TITLE
Fixed Issue #2171 - Reskin:Misalignment in Interest Rate Chart

### PR DESCRIPTION
**Pull request by wmay1991**
Fixed issue by removing label from checkbox.

### CODE REVIEW

**Comment by wmay1991** [comment]
image

**Comment by wmay1991** [comment]
image

**Comment by wmay1991** [comment]
Before the fix
image

**Comment by wmay1991** [comment]
Before the fix
image

**Comment by wmay1991** [comment]
Before fix
image

**Comment by mbj36** [comment]
Send new PR with single commit and detailed description of your fix

**Pull request closed without merging**
