### PR TITLE
creditbureau_configuration screens

### PR DESCRIPTION
**Pull request by nikpawar89**
creditbureau_configuration screens

### CODE REVIEW

**Comment by ShruthiRajaram** [comment]
Kindly format files, remove commented code  and resend the PR for review

**Comment by MexinaD** [comment]
Hello @nikpawar  did you check on the @ShruthiRajaram 's comment?

**Comment by TercioPedro** [comment]
Hello people,

I recently installed Mifos, I have some doubts about deposits, is it possible for a customer to make monthly deposit of shares in his own account without application and without charging fees?

**Comment by awasum** [comment]
WIth this: https://github.com/openMF/community-app/pull/3236 merged, can we close this PR? Or what needs to be done?

**Comment by rrpawar96** [comment]
@awasum, Yes we can close this PR.

**Comment by edcable** [comment]
Closed. PR #3236 addresses this.

**Pull request closed without merging**
