### PR TITLE
Make link on Mifos start up page plain text (MIFOSX-2809)

### LINKED ISSUE #1736: Link on the Mifos start up page is dead
Reported by Richard at https://mifosforge.jira.com/browse/MIFOSX-2809

Original Description:
The link underneath the MIFOS logo at the start up page is dead. It could be changed to plain text instead.

mifospic

### PR DESCRIPTION
**Pull request by mdew192837**
* Fixes showing of a dead link to the user

Removed the anchor tag, which contained a dead link. Instead, made it plain text. Also reformatted the code a little bit.
Fixes #1736

### CODE REVIEW

**Comment by nazeer1100126** [comment]
Instead of making plain text, can you please link it to 
https://github.com/openMF/incubator-fineract/blob/master/MIFOS-CHANGELOG.md

**Comment by mdew192837** [comment]
@nazeer1100126 Should the text change as well then? Perhaps something like "MifosX Changelog"?

**Comment by nazeer1100126** [comment]
Existing text should remain. But link should be changed to https://github.com/openMF/incubator-fineract/blob/master/MIFOS-CHANGELOG.md

**Comment by mdew192837** [comment]
@nazeer1100126 It should be ok now.

**Comment by nazeer1100126** [comment]
@mdew192837 Thank you.

**Pull request merged**
