### PR TITLE
Reskin: Fix #1798 - Validation error readable

### LINKED ISSUE #1798: Reskin&oldSkin:Not understandable error when the grace period in loan reschedule is empty
During loan reschedule, when Reschedule for Installment, Reason for Rescheduling and Submitted date is filled but the remaining fields are not filled. When submitted through an error which seems to mean the grace period for principal can not be blank but the error is not clear to a normal user.

reschedulegrace

Can be reproduced at https//demo.openmf.org by filling the form of reschedule loan but don't check on "Change Repayment Date", "Introduce Mid-term Grace Period", "Extend Repayment Period" and "Adjust Interest rate for the remainder of loan" then submit.

### PR DESCRIPTION
**Pull request by botraunak**
Fixed #1798 
Validation error added as per the comment.

Old 
screen shot 2017-05-30 at 3 06 36 pm

New
screen shot 2017-05-30 at 3 08 05 pm

To Verify: 
URL: [https://demo.openmf.org/newbeta/#/loans/1038/reschedule/](https://demo.openmf.org/newbeta/#/loans/1038/reschedule/)
Date: 22 June 2017

### CODE REVIEW

**Comment by botraunak** [comment]
@mbj36 Please review

**Comment by Mastermaulik** [comment]
@botraunak , Please follow the following convention for sending a Pull Request:

1. If the PR is for solving some Issue related to UI, post 2 pictures, first picture containing the earlier UI and the second picture containing the updated UI.
2. Include the URLs to the views that are effected by the PR. For example, if the PR has some improvements in the clients page, have the URL information as: https://demo.openmf.org/newbeta/#/clients

**Comment by botraunak** [comment]
@Mastermaulik Updated!

**Comment by Mastermaulik** [comment]
@botraunak Mention the correct URL from [https://demo.openmf.org/newbeta](https://demo.openmf.org/newbeta)

**Comment by Mastermaulik** [comment]
@santoshmath Please check if the fix works and merge this PR

**Comment by mbj36** [comment]
@botraunak In reschedule loans there are more errors which are not understandable, can you also take up all those ? It would be a very good fix then

Ping me if help needed

**Pull request merged**
