### PR TITLE
fix: Issue #2682 - Replaced left and right icons with up and down in Savings Account Summary

### LINKED ISSUE #2682: Replace Deposit and Withdraw (Left & Right Arrows) Icons with something more intuitive
## Description
On the client details page, under the Savings Summary, the quick action buttons for Deposit and Withdraw are a left and right arrow. 

Left and Right arrows are typically used for navigation which makes this confusing. Ideally representative icons could be chosen for each action but if not, an up and down arrow would make better sense here. 

See screenshot. 
screen shot 2017-12-22 at 6 43 08 am

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #2682 

@mbj36 @botraunak @edcable @gkrishnan724 Please Review it !!

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by luckyman20** [comment]
@mbj36 or @gkrishnan724 This same problem persists when you open a Savings Account. So if you can reopen the PR, I will make the necessary changes. 

capture

**Comment by mbj36** [comment]
You can create a new PR @luckyman20

**Comment by luckyman20** [comment]
@mbj36 Will do. Thanks for a quick response

**Pull request merged**
