### PR TITLE
Fix #2899 Inconsistency in the UI of the app

### LINKED ISSUE #2899: Inconsistency in the UI of the app
## Description
At the following places, the white card container has not been implemented for the content instead it resides in the old grey container which is inconsistent with the new UI:
- [x] Create GL Account
- [x] Edit GL Account
- [x] AdHoc Query
- [x] Create AdHoc Query

## Steps to Reproduce
Accounting -> Chart of Accounts -> Add Account
Accounting -> Chart of Accounts -> Select any account -> Edit
Organisation -> AdHoc Query
Organisation -> AdHoc Query -> Create AdHoc Query

## Expected Behaviour
The UI should be consistent throughout the app and thus the grey container should be updated to white, card container for the content.

## Actual Behaviour
The UI is inconsistent at few places in the app, with the new white card container not implemented for the content.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
screenshot 333
screenshot 334
screenshot 335
screenshot 336
screenshot 337

### PR DESCRIPTION
**Pull request by abhaychawla**
## Description
At the following places, the white card container has been implemented for the content instead of the old grey container which was inconsistent with the new UI:
- [x] Create GL Account
- [x] Edit GL Account
- [x] AdHoc Query
- [x] Create AdHoc Query

## Related issues and discussion
#2899 

## Screenshots, if any
screenshot 338
screenshot 339
screenshot 340
screenshot 341
screenshot 342

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by awasum** [comment]
Hi @abhaychawla . Sorry we took so long to review and merge this. I am not ready to review and merge. Please, can you pull from upstream develop branch and resolve merge conflicts on this PR so I can merge? Thanks.

**Comment by abhaychawla** [comment]
Will update as soon as possible.

**Comment by alexnavis** [comment]
Hi @abhaychawla , will you be able to resolve the conflicts ?, please let us know.

**Comment by shrunk3** [comment]
resolved conflicts and merged it

**Pull request merged**
