### PR TITLE
MIFOSX-2623/2616

### PR DESCRIPTION
**Pull request by mbj36**
First name and last name are validated 
These two text boxes only accepts character....numbers and other special character are not accepted :)

### CODE REVIEW

**Comment by UltimateSupreme** [comment]
Do not add js in html files. JS generally goes in the files inside scripts folder (usually in the relevant controller for that page).
Also, #1505 already solves this issue.

**Comment by mbj36** [comment]
@UltimateSupreme link u mentioned didn't solve the issue as required....its still accepting numbers

**Comment by rajuan** [comment]
2623:This solution will not work globally. We need to support Unicode as well. Please take the validation rules from domain experts in the community.
2616: presentation/formatting is totally different, use the existing style
always send separate PR for individual requests.

**Comment by mbj36** [comment]
@rajuan Sure i will :)

**Pull request closed without merging**
