### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by diegoc-am**
## Description

- Added a `Dockerfile`

## Related issues and discussion
#3106 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [*] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [*] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [*] If you have multiple commits please combine them into one commit by squashing them.

- [*] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by diegoc-am** [comment]
It seems that travis didn't get to communicate with github https://travis-ci.com/openMF/community-app/builds/121977161

**Comment by vorburger** [comment]
@belfazt this looks identical to @awasum's #3107 - what am I missing?

BTW just FYI you may would like to Subscribe to #3112.

**Comment by diegoc-am** [comment]
Nothing, I asked on his PR if he had time to address your comments and he said that I could go ahead

So, it's just the same with those corrections

**Comment by vorburger** [comment]
OK, got it. Merging this, sorry for the delay....

**Pull request merged**
