### PR TITLE
patch fix for datepicker issue number 3239

### PR DESCRIPTION
**Pull request by bharathcgowda**
cherry-picking the fix came on develop branch to the 18.03  for the patch release.
ISSUE:https://github.com/openMF/community-app/issues/3239

cherrypicked commit: https://github.com/openMF/community-app/commit/cbefc76f9e57c1341f0095de1b0b0e5a571ebca9

### CODE REVIEW

**Comment by awasum** [comment]
See https://github.com/openMF/community-app/pull/3242, should we close this PR?

**Comment by bharathcgowda** [comment]
@awasum that PR has been merged to Develop Branch. We need to do a patch release for 18.03 . hence i have sent a separate pull request for the 18.03 branch

**Comment by wkk91193** [comment]
@bharathcgowda Could you fix the build errors

**Review by wkk91193 — CHANGES_REQUESTED** [review]
@bharathcgowda Could you fix the build errors

**Comment by edcable** [comment]
@bharathcgowda does this no longer need to be merged since #3242 was merged?

**Comment by bharathcgowda** [comment]
@edcable this PR is for 18.03 release. #3242 has been merged to the develop branch only.
for people who are still using and use 18.03 release will still have an impact without this PR being merged.

Also, I have noticed that the issue is still accuring on dev.mifos.io, which it should not be the case, I'll take that matter in a different thread.
image

**Comment by shrunk3** [comment]
@wkk91193 could please guide me why the build is failing, Code looks good to me, and this has to be merged

**Review by shrunk3 — APPROVED** [review]

**Pull request merged**
