### PR TITLE
Made errors more descriptive

### PR DESCRIPTION
**Pull request by ad-os**
This **PR** is for this [issue](https://mifosforge.jira.com/browse/MIFOSX-2555?jql=labels%20%3D%20AngularJS) on **JIRA**.There were 3 enhancements in this issue

1. To generate first error of this issue follow the next given steps (Log in the account -> Reports -> Loans -> Select one of the loan item -> Run Report). This is how it will look 
screen shot 2016-03-03 at 11 03 01 pm 1

* After my work the warnings are now more descriptive as given below 
corrected

2 To generate second error of this issue follow the next given steps (Log in the account -> Admin -> System -> ManageCodes -> Select any code name -> Add Code Values -> Click on Add Button)

* By clicking on the add button nothing happens but some warning must be generated.
* After my work on this part of the issue, when no field is filled the warning is shown like
corrected

3 To generate the third error of this issue follow the next given steps (Log in the account -> Admin -> Products -> Loan Products -> Create Loan Product)

* The description on JIRA says that when principal field is left blank, no warning is genrated but it is already generating when principal field is left blank so I don't think any work is required here :smile:

### CODE REVIEW

**Comment by rajuan** [comment]
Please resend the request with single commit.... unnecessary commits will history bulky and meaningless.... also make sure PR contains only the changes you intend to change.

**Comment by rajuan** [comment]
Have you tested your changes on all reports?

**Comment by ad-os** [comment]
Sorry for the late reply. Yes, it is working on all the reports.I will fire a PR with one commit. Thanks :smile:

**Comment by ad-os** [comment]
Hi, I have filed a new PR at [this](https://github.com/openMF/community-app/pull/1537) link with a single commit.

**Pull request closed without merging**
