### PR TITLE
Reskin: Enhancement #2160 Add Scroll on hover

### PR DESCRIPTION
**Pull request by gkrishnan724**
Added scroll on hover and also added the scrollable tabs to places where it is required.

### CODE REVIEW

**Comment by mbj36** [comment]
@gkrishnan724 From my side, on hovering sometimes it works but most of the time it doesn't, I am using chrome browser

**Comment by mbj36** [comment]
I noticed that when i do right click, then scroll happens, it doesn't work on hovering

**Comment by gkrishnan724** [comment]
@mbj36 Its working fine for me, can you re-check?
desktop-animation

**Comment by mbj36** [comment]
@gkrishnan724 This doesn't work on my PC, When i do right click on arrow, then scroll starts

**Comment by Mastermaulik** [comment]
@santoshmath please check this PR across different browsers and provide feedback

**Comment by Mastermaulik** [comment]
@gkrishnan724 not working on my PC as well. I checked it on Safari Browser and chrome, doesn't work in both browsers.

**Comment by gkrishnan724** [comment]
@Mastermaulik @mbj36 Can you check it now? I made some changes and I decreased the speed a little bit. It's working for me in chrome and Firefox

**Comment by mbj36** [comment]
Checking after your update - On clicking left arrow, scroll happens right

**Comment by Mastermaulik** [comment]
@mbj36 @gkrishnan724 speed looks ok now

**Comment by mbj36** [comment]
Does left arrow works right ? @Mastermaulik

**Comment by gkrishnan724** [comment]
Screenshot
scroll1

**Pull request merged**
