### PR TITLE
Reskin: Fix #1822 - Asterisks are missing in the fields of creation of Cashier to show mandatory fields

### LINKED ISSUE #1822: Reskin&oldSkin: Asterisks are missing in the fields of creation of Cashier to show mandatory fields
Also reported at https://mifosforge.jira.com/browse/MIFOSX-2827

In the form to create a Cashier for Teller the fields "Cashier/Staff", "From" and "To" are mandatory but there is no asterisks to show that, only when you submit without filling them is when you will know.

cashier

### PR DESCRIPTION
**Pull request by Anh3h**
Earlier UI:
c1

Previous UI:
p1

Affected View: https://demo.openmf.org#/tellers/35/createCashierForTeller

### CODE REVIEW

**Comment by botraunak** [comment]
Duplicate #2271

**Comment by Anh3h** [comment]
ok.
Will close this then

**Comment by mbj36** [comment]
@Anh3h You can work on another issue :)

**Comment by Anh3h** [comment]
Sure. I will indicate on the issues so I don't work on an issue another person is currently working on. :)

**Pull request closed without merging**
