### PR TITLE
FINERACT-1375:ClientEntityFix

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by rrpawar96** [comment]
Hi @luckyman20, We have made a few changes after the last ClientEntity PR got merged on community-app  https://github.com/openMF/community-app/pull/3444

Instead of 'replacing' the dropdown of m_client with m_client_person and m_client_entity.
We have noticed that it was breaking few testcases in backend, so we found alternative way as

while creating Datatables, keeping m_client as it is and we will 'add' new parameter attaching to it, which will store new value either PERSON or ENTITY.
and while viewing clients, the datatables will be fetched respectively, ie. PERSON datatable to Client (Type:Person) and ENTITY datatable to Client (Type: Entity)

**Comment by rrpawar96** [comment]
create_datatable

person_datatable

entity_datatable

**Comment by rrpawar96** [comment]
FINERACT BackEnd is been merged: https://github.com/apache/fineract/pull/1979

**Comment by er-prince** [comment]
There is a small issue , i have tested it. 

1) make a datatable it works fine .
2) edit the same datatable , 

Application Table Name

Screenshot 2022-01-08 at 1 56 34 PM

if we try to save it will throw  error
Screenshot 2022-01-08 at 1 59 27 PM

**Comment by rrpawar96** [comment]
Thanks, @er-prince for performing testing, The edit-datatable screen issue is been fixed, can you please do re-testing and confirm if everything is fine.

**Comment by er-prince** [comment]
> Thanks, @er-prince for performing testing, The edit-datatable screen issue is been fixed, can you please do re-testing and confirm if everything is fine.

Sure @rrpawar96  i will do test now , will report back soon.

**Comment by er-prince** [comment]
> Thanks, @er-prince for performing testing, The edit-datatable screen issue is been fixed, can you please do re-testing and confirm if everything is fine.

Its perfect now. working as expected . Thanks @rrpawar96

**Comment by rrpawar96** [comment]
Hi @bharathcgowda, can you please merge this PR

**Comment by bharathcgowda** [comment]
Hi @luckyman20  could you please review this PR?

**Review by luckyman20 — COMMENTED** [review]
Code quality wise looks good. Can't comment on functionality.

**Pull request merged**
