### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by vorburger**
$ npm audit

found 219 vulnerabilities (103 low, 35 moderate, 80 high, 1 critical) in 3503 scanned packages
  run `npm audit fix` to fix 54 of them.
  100 vulnerabilities require semver-major dependency updates.
  65 vulnerabilities require manual review. See the full report for details.

$ npm audit fix

added 4 packages from 19 contributors, removed 2 packages, updated 16 packages and moved 3 packages in 4.907s

fixed 54 of 219 vulnerabilities in 3503 scanned packages
  65 vulnerabilities required manual review and could not be updated
  12 package updates for 100 vulnerabilities involved breaking changes

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum @maektwain @tonic889 @sluipmoord @OussEmaDevCode @m-sameer @punwai @luckyman20 @DeeJayBro @muskankhedia (all recent contributors) is this OK?  Would one you be interested in contributing to fixing the other open security vulnerabilities of this project?

**Comment by maektwain** [comment]
Looks like a lot of work I think we should simply do an automatic upgrade provided by npm. 

I will look into it.

**Comment by awasum** [comment]
Go ahead. I had also done some of it last year. See https://github.com/openMF/community-app/pull/3146

**Comment by maektwain** [comment]
@awasum  Did you do it manually? It seems like this project is really outdated , we might need some kind of package update every once in a while.  What about audit fix --force?

**Comment by maektwain** [comment]
Seems like most of the version's are old and outdated , I think we might need to really think through if we want to support this old version of community app. While upgrading such packages, you lead to upgraded version and breaking the application(anyway that is going to happen)

And then fixing those things. Better we provide support on the upgrade on the web-app which is getting developed on newer version of the Angular.

**Comment by maektwain** [comment]
@vorburger https://github.com/maektwain/community-app/pulls

**Comment by maektwain** [comment]
It seems like we have low level vulnerabilities, which in case can be ignored.

**Comment by maektwain** [comment]
https://travis-ci.org/github/maektwain/community-app/builds/680235848 its failing at upgrading some dependency

**Comment by maektwain** [comment]
@awasum @vorburger @frankmt Someone can help fix this https://travis-ci.org/github/maektwain/community-app/builds/680237585?utm_source=github_status&utm_medium=notification

**Comment by maektwain** [comment]
I advise others not to pick this up , I am doing a complete upgrade so that we start with fresh ground.

My strategy is simple, I am using dependbot , it might have some breaking change where others can help.

Thanks

**Comment by maektwain** [comment]
So far,
found 155 vulnerabilities (55 low, 35 moderate, 64 high, 1 critical) in 2825 scanned packages
and now some test are breaking.

**Comment by vorburger** [comment]
> @awasum @vorburger @frankmt Someone can help fix this
> it might have some breaking change where others can help.

@maektwain just to avoid any wrong expectations - I personally won't be able to help further here, just because my JS skills are very limited... :smile_cat: so I'll have to ignore further updates. But if this PR motivates others to jump, that would be great!

What confuses me a little bit is whether perhaps there was a slight misunderstanding - this is a PR, not a bug, in which I'm proposing to at least already upgrade a few dependencies which `npm audit fix` made when I ran it locally. Does anyone have any objections that we at least already merge this PR, as it is? Or is that risky?

More work would be great of course - but that should go onto separate new PRs (and related discussions in a new bug you can create), not this PR here, which will close after merge - would that make sense?

**Comment by maektwain** [comment]
If we completely upgrade the npm dependency so we might end up breaking some functionality. Obviously it should be top priority to close all these vulnerability. Not all. 

What I see at least the npm dev dependencies should be at least updated which what I am doing. 

Maybe opening up new PR could be the right approach. 

I think it does not make any difference if we merge this since these vulnerability will appear once more as the packages start getting older. 

We need to at least close the severe security packages.

**Pull request merged**
