### PR TITLE
Removed all duplicates from locale-en.json.

### PR DESCRIPTION
**Pull request by DeeJayBro**
## Description
Removed all the duplicates from the english translation files
## Related issues and discussion
#3141 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Review by muskankhedia — APPROVED** [review]
@DeeJayBro Thanks for showing your interest. Nice Work!

@abhaychawla @santoshconflux Sir, I have reviewed the PR, it removes all the redundant keys keeping on mind that keys should be present only once in the file and now the file contains all the keys only once. Please have a look.

**Comment by jonathanzhang53** [comment]
lgtm as well. I see that some keys were actually assigned to multiple values, which one value was also removed, but you guys will have to make sure the right one was taken out.

**Comment by muskankhedia** [comment]
@jonathanzhang53 Sir, I kept that in mind while reviewing. And as much as I have been through the local-en.json file, the keys were repeated in the file but all of them had the same value(some of the value only differ in the case), so we just need to remove the keys defined multiple time to decrease redundancy in the file. 
*For Example: the key **Button** is repeated 14 times with the same value **".."**.*

**Review by abhaychawla — CHANGES_REQUESTED** [review]
Hi @DeeJayBro, please ensure that you create a separate branch to make you changes instead of making them directly in the develop branch. Follow the steps specified here: https://github.com/openMF/community-app/blob/develop/Contributing.md
Close this PR and resend it after making the required changes in a separate branch. Make sure your commit message is also as per the guidelines in CONTRIBUTING.md
Feel free to ask questions, if you have any.

The keys starting with # are meant for identification within the file for a particular section and need not be considered as redundant. Please don't remove those. Only remove redundancies such as  label.heading.debitaccount occurring multiple times in a single section. If a single key is occurring multiple times but in different sections shift them them under #Common under the correct key and remove them from those sections where it was occurring multiple times. My apologies, as this was not specified before correctly. Make the required changes.

**Comment by DeeJayBro** [comment]
@abhaychawla Therme wie no Commit Guidelines in the contribution.md. And second I don't really know what changes I should do to the branches because it should be merged with the upstream develop branch

**Comment by muskankhedia** [comment]
@DeeJayBro working on a separate branch instead of the develop branch means you need to create a different branch in your forked the repo to work and later make a PR to the develop branch of the main repo. This will help you maintain the code well according to different issues in the repository and will help you work on different issues at the same time. If you haven't used branches before and want to learn more about it, you can refer to [video](https://youtu.be/sgzkY5vFKQQ).

**Comment by abhaychawla** [comment]
@DeeJayBro Have a look at the instructions here: https://github.com/openMF/community-app/blob/develop/Contributing.md#submit-pr
Yes, it will be merged into the develop branch but you should do the changes in a separate branch as a best practice. By changes I meant the changes required to solve this issue.

**Pull request closed without merging**
