### PR TITLE
Fix #2757 Popover keeps on flashing in Create User

### LINKED ISSUE #2757: Popover keeps on flashing in Create User
## Description
The popover message for Override password expiry policy in create user section keeps on flashing and thus cannot be read properly.

## Steps to Reproduce
Admin -> Users -> Create User -> Hover the mouse over question mark sign for Override password expiry policy

## Expected Behaviour
Popover should be visible on hovering the mouse over question mark sign

## Actual Behaviour
Popover keeps on flashing on hovering the mover over question mark sign

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
screenshot 68

### PR DESCRIPTION
**Pull request by abhaychawla**
## Description
Popover message is now visible while mouse hovers over the question mark icon, earlier it kept on flashing.

## Related issues and discussion
#2757 

## Screenshots, if any
Before:
screenshot 68
After:
screenshot 69

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@abhaychawla, Thanks! but could you please fix this issue for all places in the community-app? I think there might be more places where this issue occurs.

**Comment by abhaychawla** [comment]
Yes, will search and do.

**Comment by abhaychawla** [comment]
@gkrishnan724 I looked throughout the app to find anymore flashing popovers but there wasn't any other place I could find a similar issue till now. But, earlier I had found a similar issue #2766 along with a validation issue in floating rate section which I fixed separately. Shall I combine the work of both the pull requests?

Also, although the popovers aren't flashing elsewhere in the app there is a separate issue regarding their placement which occurs in most places in the app as you can see in one of the screenshots provided below. I can work on it. Shall I create a separate issue for this or modify in this issue itself?
screenshot 241

**Comment by gkrishnan724** [comment]
@abhaychawla please create a seperate issue and PR for those

**Comment by abhaychawla** [comment]
Okay!

**Pull request merged**
