### PR TITLE
Fixes #2965 : Show Joined On filed as mandatory with late validation

### LINKED ISSUE #2965: On employee creation, "joined on" field has no sign of showing it mandatory
## Description
When creating an employee, a joined on filled has no sign of showing its mandatory

## Steps to Reproduce
Go to Admin, then Organisation, then manage employee, create employee, fill all the fields except the "joined on" field, when you submit you will get an error that the filed can not be blank

## Expected Behaviour
The field should have the sign to show that it should not be left blank

## Actual Behaviour
There is no sign to show the field is mandatory

## Settings
- Mifos X version: 18.03
- Browser used: Chrome

## Screenshots, if any
joinedon

### PR DESCRIPTION
**Pull request by bauripalash**
## Description
Describe the changes made and why they were made instead of how they were made.
Added necessary code to show `Joined On` field as mandatory and added late validation to it

## Related issues and discussion
#2965 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Review by gkrishnan724 — CHANGES_REQUESTED** [review]
@bauripalash  please squash the commits into a single commit:

Here is how you can do it:

1. `git reset HEAD~2` This will remove the  2 commits from the top of your branch but will still keep the changes.

2. `git add -A` add all the changes 

3. `git commit -m "Fix #2965 - Show Joined field as mandatory " ` - Put proper commit message

4. `git push -f origin bauripalash-fixfor-2965` - Push the changes.

The PR will update automatically after you do the commands
Feel free to ping me if you have any questions on the above.

**Comment by bauripalash** [comment]
@gkrishnan724 is this okay now?
By the way thanks for your help!

**Review by gkrishnan724 — APPROVED** [review]
Good job! thanks

**Comment by bauripalash** [comment]
Thank You!😄

**Pull request merged**
