### PR TITLE
Issue 1955

### PR DESCRIPTION
**Pull request by botraunak**
Now navbar is fixed on top and also fixed the small height of sidebar issue.

### CODE REVIEW

**Comment by mbj36** [comment]
@botraunak when you work on any issue, see if others are working or not

**Comment by botraunak** [comment]
@mbj36  Will keep that in mind Thanks!

**Comment by mbj36** [comment]
Have you compiled sass ?

**Comment by botraunak** [comment]
@mbj36  Yes, I've made changes to the styles in the sass directory and I guess grunt serve compiles them on the fly?

**Comment by Mastermaulik** [comment]
The changes made to the styles-dev directly are not directly compiled by grunt. You have to install a tool called compass as shown in the link [here](http://compass-style.org/install/)

After installing this, you have to run the command:
sass styles.css > ../../styles/styles.css

Then, the changes that are made to the scss files, would be translated and visible.

Can you go through this process and then send the PR?

**Comment by Mastermaulik** [comment]
Also, @botraunak I tried your changes locally, the home screen looks like this on mobile devices:

screen shot 2017-03-02 at 10 25 15 am

It should look like this:

screen shot 2017-03-02 at 10 26 42 am

Also, make sure that there is some padding between the top nav bar and our view, the view should be centrally aligned as shown here:
screen shot 2017-03-02 at 10 27 14 am

**Comment by botraunak** [comment]
@Mastermaulik I've done the requested changes for mobile view and build with sass like you said, please review them :) I'll squash the commits one you approve.

**Comment by Mastermaulik** [comment]
Here, in mobile view, the view hides behind the top nav-bar like this:

screen shot 2017-03-02 at 11 06 25 am

Actually it should be something like this:
screen shot 2017-03-02 at 11 06 25 am

**Comment by botraunak** [comment]
@Mastermaulik Just a suggestion the header needs to fixed in position. so by default the top navbar,it should be closed. and if he scrolls down in bigger pages with a lot of content in tables. he should still be able to open the top nav bar 
screen shot 2017-03-02 at 11 33 22 am

**Comment by mbj36** [comment]
@botraunak Multiple commits not allowed, send final PR with single commit. Changes look good to me

**Pull request closed without merging**
