### PR TITLE
Docker build fix

### PR DESCRIPTION
**Pull request by xurror**
## Description
I've been trying to run the docker build locally for some tests for a feature which I want to implement on fineract(https://issues.apache.org/jira/browse/FINERACT-845) and it continuously failed. Turns out the were was a problem with the bundle version in the container. Didn't see any reported issue or opened PR for this(maybe I just missed it).

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by xurror** [comment]
@vorburger, @awasum can you review this?

**Comment by vorburger** [comment]
Hm, that's interesting, why are Builds on https://hub.docker.com/r/openmf/community-app/builds working without this? Maybe this actually isn't needed? Or only for "serve"? If we don't "need" it, perhaps it's better to keep the Dockerfile simpler? If it is required (or "useful"), we should document how / for what?

**Comment by xurror** [comment]
Actually very weird. Tried this yesterday and earlier this morning but it didn't go well.
Local build still fails without the patch but running directly from dockerhub works fine

**Comment by xurror** [comment]
Perhaps this change isn't necessary afterall. pulling directly from dockerhub resolves my problem with fineract update. I'll just close this then

**Pull request closed without merging**
