### PR TITLE
Jira Issue MIFOSX-2081

### PR DESCRIPTION
**Pull request by Akanksha08**
Dropdown now translates office.name and staff.displayName in the create group view.

### CODE REVIEW

**Comment by gauravsaini03** [comment]
@Akanksha08 I pulled your code and tested for this translation it didn't directly worked for me. To run your existing code you have to make $scope.translate = $translate in controller.

Although, Please look at this http://stackoverflow.com/questions/23568180/how-to-ng-translate-inside-select-box-option-in-angularjs
Looks like recommended way to do it. Please test it again and let me know will review it again :)

**Comment by Akanksha08** [comment]
@gauravsaini03 I went through the link you gave and made the recommended changes. Please check.

**Comment by gauravsaini03** [comment]
@Akanksha08 Please squash your commits in single commit. So, we can merge this PR.

**Comment by Akanksha08** [comment]
@gauravsaini03 I sent this PR from the user interface and I don't know how to squash using github UI.
Could you please help?

**Comment by rajuan** [comment]
Take a look at the end of this page https://github.com/openMF/android-client/wiki/Git- <https://github.com/openMF/android-client/wiki/Git-&-Github> &-Github

 

Regards,

Adi

**Comment by Akanksha08** [comment]
@rajuan I went through that link. I want to know if there is any way to do it from the github GUI?

**Comment by gauravsaini03** [comment]
@Akanksha08 No you have to do it via CLI or use some git tool at your end.
I would recommend best way will be do it via CLI.

**Comment by Akanksha08** [comment]
@gauravsaini03  I tried squashing commits. I did it by checking out branch on my local machine. Then I tried to push my changes to my forked repo. I got an error that I need to pull changes first. So I did that and again pushed the changes. Now I see that there are 4 commits in my repo which is not desired.

Could you please help?

**Pull request closed without merging**
