### PR TITLE
fix #2755- overflow fixed

### LINKED ISSUE #2755: Overflow of table header in Incentives popup
## Description
Overflow of table header in Incentives popup

## Steps to Reproduce
Products -> Fixed Deposit-> Products  -> Interest Rate Charts -> Create Interest -> Rate Chart Incentives

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
commun

### PR DESCRIPTION
**Pull request by anweshknayak**
## Description
Overflow fixed.

## Related issues and discussion
#2755

## Screenshots, if any
screenshot from 2018-01-09 17 30 36

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@anweshknayak, please fix the same issues in, Create Fixed deposit, Create Recurring, edit recurring deposit

**Comment by anweshknayak** [comment]
@gkrishnan724 done :smile:

**Comment by gkrishnan724** [comment]
@anweshknayak  Please squash your commits into one, Follow these:

1. `git reset HEAD~2` - This deletes the top two commits and keeps the changes.
2. `git add -A`  - Add the combined changes of both the commits
3. `git commit -m "Fix #2775- Overflow fixed"` - Commit the combined changes
4. `git push -f origin overfl` - Force push the changes.

**Comment by anweshknayak** [comment]
@gkrishnan724 somehow messed this up again. :smile:  Sorry . This will not happen again. Please refer #2918

**Pull request closed without merging**
