### PR TITLE
Fix #2707 - UI bug in "cashiersForTeller" page

### LINKED ISSUE #2707: UI bug in "cashiersForTeller" page
## Description
The row containing the text input field and new cashier button is slightly going down due to text above it. 

## Steps to Reproduce
Go to admin > organization > teller/cashier > click on any teller
## Expected Behaviour
The container of the row should adjust height according to content
## Actual Behaviour
The container has fixed height.
## Settings
- Mifos X version: 17.07.01.RELEASE 
- Browser used: Firefox

## Screenshots, if any
screenshot from 2018-01-02 13-11-41

### PR DESCRIPTION
**Pull request by jervis446**
## Description
I adjust the height row containing the text input field and new cashier button .
## Related issues and discussion
#2707

## Screenshots, if any
screenshot-2018-1-2 mifos x client 1

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by jervis446** [comment]
Hi,@mbij36  PTAL

**Comment by gkrishnan724** [comment]
@jervis446 Please follow the commit template `Fix #<issue-no> - <issue-desc>`

**Comment by gkrishnan724** [comment]
@jervis446 Please follow the commit template `Fix #<issue-no> - <issue-desc>`

**Comment by jervis446** [comment]
Ok @gkrishnan724

**Comment by jervis446** [comment]
@gkrishnan724 PTAL

**Comment by gkrishnan724** [comment]
Thanks @jervis446 !

**Comment by jervis446** [comment]
@gkrishnan724 this PR haven't merge since last 14 days !

**Pull request merged**
