### PR TITLE
FINERACT-1391:AccountNumberPrefix

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by rrpawar96** [comment]
FINERACT: https://github.com/apache/fineract/pull/1985

**Comment by rrpawar96** [comment]
@bharathcgowda @awasum @francisguchie, Please review the PR, the backend of this feature is already merged.

**Comment by bharathcgowda** [comment]
@luckyman20  @BLasan could any one of you help in review of this PR please?

**Review by luckyman20 — COMMENTED** [review]
On a quick look, there are some indentation issues, you may fix them by auto-formatting through your editing.

Also, it would be helpful if you can attach screenshots of the changes you have made.

**Comment by francisguchie** [comment]
> ` [df3c4bc](/openMF/community-app/pull/3450/commits/df3c4bc2e7574580a73be64f8cf08bd72d35208a) `
> [@rrpawar96](/rrpawar96)

@rrpawar96  @luckyman20 

would this help??

image

**Comment by rrpawar96** [comment]
Prefix-UI

Only 3rd Step Screen UI is changed a bit

**Comment by rrpawar96** [comment]
@bharathcgowda, Fixed Indentation, ready to get merged

**Review by luckyman20 — APPROVED** [review]
LGTM!

**Pull request merged**
