### PR TITLE
Fixed 3249 :FINERACT-1043: Not able to create the client address due to missing street field in UI

### PR DESCRIPTION
**Pull request by kiran-vsm**
…

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Review by spider0061 — COMMENTED** [review]
@kiran-vsm I tested your PR the street field has been added in create client and edit address component. For create client it is working but for edit address, it is not working. Also, the street field should also be present in the add address component. Change your commit and PR message as per the guidelines.

**Comment by edcable** [comment]
Thank you @spider0061. @kiran-vsm are you able to address those requested changes?

**Review by wkk91193 — CHANGES_REQUESTED** [review]
Could you reference the issue, in the issue number section @kiran-vsm

**Comment by bharathcgowda** [comment]
can any Dev who is maintaining this Repo Review and merge this issue?

**Comment by edcable** [comment]
@kiran-vsm per @spider0061 it looks like there street field is still missing from the add address component.

**Comment by kiran-vsm** [comment]
@edcable: At the time of bug fixing fineract code base is [#FINERACT-1043](https://github.com/apache/fineract/pull/1110), [FINERACT-1022](https://github.com/ptuomola/fineract/tree/FINERACT-1022). Later on PR's, **street** field configuration itself deleted from the DB **m_field_configuration** table, so now the user can not capture the **street** information.

**Comment by spider0061** [comment]
> @edcable: At the time of bug fixing fineract code base is [#FINERACT-1043](https://github.com/apache/fineract/pull/1110), [FINERACT-1022](https://github.com/ptuomola/fineract/tree/FINERACT-1022). Later on PR's, **street** field configuration itself deleted from the DB **m_field_configuration** table, so now the user can not capture the **street** information.

@kiran-vsm can you update the PR accordingly. If the field is not present in the database then I don't think there is any need for this issue now.

**Comment by kiran-vsm** [comment]
> > @edcable: At the time of bug fixing fineract code base is [#FINERACT-1043](https://github.com/apache/fineract/pull/1110), [FINERACT-1022](https://github.com/ptuomola/fineract/tree/FINERACT-1022). Later on PR's, **street** field configuration itself deleted from the DB **m_field_configuration** table, so now the user can not capture the **street** information.
> 
> @kiran-vsm can you update the PR accordingly. If the field is not present in the database then I don't think there is any need for this issue now.

@edcable  @spider0061 

Recently address API response structure is changed. So it has broken the client address capture module. 

**Note**: Fixed this bug on the top of fineract and community develop branch.

So if this PR gets merged then the client address module will sink with the backend API request and response. Then it will start working...

Street code will not cause any issues. If the backend DB configuration does not exist then it will not display else it will display.

**Comment by bharathcgowda** [comment]
@abhaychawla  or anyone who can review and Merge the PR, Please review this ASAP, as it is causing major issues for maintaining and storing client's addresses currently.

**Comment by spider0061** [comment]
@edcable @bharathcgowda I am getting following errors when I try to build the app. This error is not because of changes made by @kiran-vsm. @kiran-vsm are you able to build the app? 
Screenshot from 2020-10-23 20-59-22

**Comment by bharathcgowda** [comment]
@spider0061  Hi Ashutosh, Could you post that in our community forum? Other contributors who know this would be able to help you out.

**Comment by edcable** [comment]
@wkk91193 are you able to get this change to build?

**Comment by spider0061** [comment]
Closing this as PR #3344 solves this and contributor is not active.

**Pull request closed without merging**
