### PR TITLE
Fix #3080 - Fixed Term step validation

### LINKED ISSUE #3080: In share Product creation process, after entering all mandatory values for 'Terms' step , the navigation wizard indicates that all mandatory values are not added for 'Terms' step
1) Go to Admin>Products>Share Products> Create Share Product.
2) Go step by step and enter all the values in 'Terms' step and go to next step:
> Terms step navigation wizard shows all mandatory values are not entered. check the screenshot.

share product creation

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Fixed validation issue in Product -> Shared Products -> Create Shared Product -> Terms Tab 

## Related issues and discussion
#3080 

## Screenshots, if any
Screenshot from 2020-10-30 17-56-58

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@spider0061 Please review

**Review by spider0061 — APPROVED** [review]
Looks Good! :+1:

**Comment by spider0061** [comment]
@bharathcgowda @edcable it looks good. Shall we merge it?

**Comment by bharathcgowda** [comment]
@spider0061 I think you can if it looks good

**Pull request merged**
