### PR TITLE
Default list of only active employees #2432

### PR DESCRIPTION
**Pull request by nnatarajan**
## Description

Please reference https://github.com/openMF/community-app/issues/2432

I found this issue on JIRA,  [Fineract-519](https://issues.apache.org/jira/browse/FINERACT-519), which I closed there due to this appearing to be only a front end issue.

Original request was to the ability to delete employees. It was discussed that as with financial software, it is better to not delete employees. Instead, it was decided to reflect only active employees by default.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by awasum** [comment]
Mifos X and Fineract are different communities. Create a corresponding issue for this work here on Github issues. https://github.com/openMF/community-app/issues

**Comment by awasum** [comment]
@MexinaD want to review this and merge?

**Comment by awasum** [comment]
> Mifos X and Fineract are different communities. Create a corresponding issue for this work here on Github issues. https://github.com/openMF/community-app/issues

There is one here: https://github.com/openMF/community-app/issues/2432 link it to this PR and attach a screenshot of the solution..

**Comment by nnatarajan** [comment]
@awasum , if this is merged, should I close the Fineract issue and mark the Community App issue as resolved?

**Comment by awasum** [comment]
> @awasum , if this is merged, should I close the Fineract issue and mark the Community App issue as resolved?

Yes. Looks like the issue on Fineract was not suppose to be there as this seem to be a front end only issue on the community app. Fineract JIRA is just for the backend Fineract issues and this community app has its own issue tracker on github.

**Comment by awasum** [comment]
> > Mifos X and Fineract are different communities. Create a corresponding issue for this work here on Github issues. https://github.com/openMF/community-app/issues
> 
> There is one here: #2432 link it to this PR and attach a screenshot of the solution..

@nnatarajan do you want to do this? Fill in the description of the PR.
image
Add screenshots, issue etc...

**Comment by nnatarajan** [comment]
@awasum , I updated the description. However, when I am run grunt validate, I am getting a network error, alerting that it will skip to the next file.

**Comment by awasum** [comment]
Screenshot?

**Comment by nnatarajan** [comment]
@awasum, It appears that there is a validation is attempting to happen on all of the application files, as it is still running.

The concern is the Network error and Skipping to the next file.

I have copy-pasted terminal:

(base) natashan:community-app natasha$ grunt validate
Running "jshint:all" (jshint) task
>> Report "jshint-log.xml" created.

Running "validation:files" (validation) task
Validation started for.. app/views/_leftnav.html
(node:2629) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Network error re-validating.. 1 
Validation started for.. app/views/_leftnav.html
Network error re-validating.. 2 
Validation started for.. app/views/_leftnav.html
Network error re-validating.. 3 Skipping to next file..
Validation started for.. app/views/_topnavbar.html
Network error re-validating.. 1 
Validation started for.. app/views/_topnavbar.html
Network error re-validating.. 2 
Validation started for.. app/views/_topnavbar.html
Network error re-validating.. 3 Skipping to next file..
Validation started for.. app/views/accounting/accounting.html
Network error re-validating.. 1 
Validation started for.. app/views/accounting/accounting.html
Network error re-validating.. 2 
Validation started for.. app/views/accounting/accounting.html
Network error re-validating.. 3 Skipping to next file..
Validation started for.. app/views/accounting/accounting_coa.html

**Comment by nnatarajan** [comment]
@wkk91193 as this is my first Community App issue, is the above grunt validate response normal?

@Sanyam96 , @rahulg963, adding you on this question should you have feedback?

**Comment by wkk91193** [comment]
@nnatarajan You can igonre this for now.

**Comment by nnatarajan** [comment]
@wkk91193 , thanks for the okaying this one. I can merge this. Should I select the option for rebase and merge?

**Pull request merged**
