### PR TITLE
Mifosx 2655

### PR DESCRIPTION
**Pull request by DanCarl857**
Added glossary entries and coded tooltips for the admin/organization page.

### CODE REVIEW

**Comment by rajuan** [comment]
Send single commit. Do not include unnecessary files.
Tool tips generally explain the UI element. you have provided links. Is this requested by someone to provide tooltip with url page? Please validate requirements with domain experts thru mifos-users@lists.sourceforge.net email

**Comment by DanCarl857** [comment]
@rajuan Please could you clarify me on what the unecessary documents are so I remove them. Also I followed the instructions to add the links in  the tooltip from this document found: https://docs.google.com/spreadsheets/d/1nT_j9jBy-laroQBc139IaD0d2A66Y-k8mdafCV5bTvc/edit#gid=0

Please if that is not what I am to do could you please clarify as the new issue I intend to work on has the same instructions.

I will squash all the commits into one.

Thanks.

**Comment by rajuan** [comment]
@DanCarl857 Please use the descriptions in the urls provided in the doc mentioned by you, come up with a 1 or 2 line statements that accurately describe the field/icon and use it as text for tooltip. An URL in tooltip will not be actionable and will not be useful.
your PR has et and test.patch as new files added to repo. Are these required for your solution?

**Comment by DanCarl857** [comment]
No those files are nt necessary. Thanks I will add the descriptions and
resubmit the pr

**Comment by DanCarl857** [comment]
Hi openMF/community-app,
A message from Daniel Carlson was left on IQ Elite for you. 
Click here https://a.iqelite.com/j/NHVo5Q/5ec/ to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=8e30566e&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by DanCarl857** [comment]
Hello,

Jack Ryan  started using IQ Elite. He  wrote you a message.

To read the message before it expires, just click on this link: https://a.iqelite.com/entry/new_message/2beaa04b7aa20f5827489c2d3fda9e1f544b80bfb/320c612f7502e5151899083b0bec460b7a87b5f58515f8ab0bd58585f51748951896ec45f6eccb659a87cc5bd91c47ccb67a86d8990749060b7cb51515151515151585866585183c483cb9060a8587b91b7c451898959c4589074c320c612f75044d3e22edb35af44b80bfb/

Read your message before it expires!            

Regards,
IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=8e30566e&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by DanCarl857** [comment]
Hello,

Your friend Jack Ryan sent you a message 36h days ago, which is still unread.

Within 24 hours the message will be deleted.

If you are curious to what Jack Ryan wrote you click here: https://a.iqelite.com/entry/new_message/2beaa04b7aa20f5827489c2d3fda9e1f544b80bfb/320c612f7502e5151899083b0bec460b7a87b5f58515f8ab0bd58585f51748951896ec45f6eccb659a87cc5bd91c47ccb67a86d8990749060b7cb51515151515151585866585183c483cb9060a8587b91b7c451898959c4589074c320c612f75044d3e22edb35af44b80bfb/            

Regards,
IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: https://a.iqelite.com/common/unsubscribe/?code=8e30566e&email=reply@reply.github.com
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Pull request closed without merging**
