### PR TITLE
Fixed the issue #2503

### PR DESCRIPTION
**Pull request by luckyman000786**
Fixed the issue #2503. Please review and merge it.
@naman14 @therajanmaurya

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@mbj36 Please review

**Comment by luckyman000786** [comment]
I think tooltip placement should be on top, and I know that it is not appropriate solution but now it is clickable because tooltip is now not overlapping with the icon. So I request you to kindly implement it and see if it is working or not.

**Comment by luckyman000786** [comment]
@mbj36 Please review it.

**Comment by mbj36** [comment]
Changes Looks Good. Please squash your commit

**Pull request merged**
