### PR TITLE
fix #2776 - remove button should be more bold

### LINKED ISSUE #2776: Remove button should be more bold and informative
## Description
Remove button should be more bold and informative

## Steps to Reproduce
Client -> Create client -> Add family members -> Remove

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any

screenshot from 2018-01-07 19 24 00

### PR DESCRIPTION
**Pull request by anweshknayak**
## Description
Remove button is bolder and can be actually noticed by the user properly

## Related issues and discussion
#2776 

## Screenshots, if any
screenshot from 2018-01-09 23 05 41

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@anweshnayak, merge conflicts please resolve them.

**Comment by anweshknayak** [comment]
@gkrishnan724 done :smile: . It's been really awesome working with you people :tada:

**Comment by gkrishnan724** [comment]
@anweshknayak please maintain a single commit, squash the commits and this should be good to go :)

**Comment by anweshknayak** [comment]
@gkrishnan724 messed this branch. Please check #2915 .

**Pull request closed without merging**
