### PR TITLE
fix #2805 - tabular views made responsive

### LINKED ISSUE #2805: More responsive for mobile/tablet view
## Description
Make the website more responsive to mobile/tablet view.

## Steps to Reproduce
Use mobile/tablet size to view the site. Some functionality doesn't work.
Use media queries to solve the problem. 

## Settings
- Mifos X version: 
- Browser used:

### PR DESCRIPTION
**Pull request by muddlebee**
## Description
tabular views made responsive

## Related issues and discussion
#2805

### CODE REVIEW

**Comment by botraunak** [comment]
Can you look into the merge conflicts and submit this PR after removing the loader and gruntfile diff. Rebase this PR. I will review once you do that.

**Comment by muddlebee** [comment]
@botraunak please review #2955 . this pr is on top of that

**Comment by edcable** [comment]
@spider0061 This old PR from @anweshknayak is still valuable to incorporate but now has a number of merge conflicts. I don't think Anwesh is active any longer on this project so was hoping you might be able to address. Anwesh - if you are still interested in contributing - we'd love to have you active again but I understand if not.

**Comment by edcable** [comment]
@wkk91193 or @spider0061 Would you be able to address the merge conflicts here for this PR?

**Pull request closed without merging**
