### PR TITLE
FINERACT-1658:Fix_GroupFilter_In_Center

### PR DESCRIPTION
**Pull request by rrpawar96**
https://issues.apache.org/jira/browse/FINERACT-1658

### CODE REVIEW

**Comment by francisguchie** [comment]
@rrpawar96  will test this end of day today

**Comment by rrpawar96** [comment]
CreateCenter
addgroups
addgroup

**Comment by rrpawar96** [comment]
@luckyman20, Please review this PR. The backend fix is been merged : https://github.com/apache/fineract/pull/2424

**Review by luckyman20 — APPROVED** [review]
LGTM!

@bharathcgowda I believe we have tested this manually to ensure that we aren't missing on any edge cases.

**Pull request merged**
