### PR TITLE
Fix #2842 - Added pagination

### LINKED ISSUE #2842: Paging missing
## Description
Paging missing in these places. Paging should be like present in Clients, Groups etc, so, that user doesn't have to scroll and scroll.

- [ ] Loan Products
- [ ] Savings Products
- [ ] Share Products
- [ ] Fixed Deposit Product
- [ ] Recurring Deposit Product
- [ ] Charges
- [ ] Manage Offices
- [ ] Manage Employees
- [ ] Provisioning Criteria
- [ ] Teller/Cash Management
- [ ] Manage Data Tables
- [ ] Manage Codes
- [ ] View Roles
- [ ] Manage Hooks
- [ ] Manage Reports
- [ ] All Reports
- [ ] Global Configurations
- [ ] Users
- [ ] Chart of Accounts

## Expected Behaviour
Paging should be present 
## Actual Behaviour
Paging is missing.
## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google-Chrome, Firefox

### PR DESCRIPTION
**Pull request by ankit01ojha**
## Description
Added pagination to the listed places.

## Related issues and discussion
#2842 

## List:-

- [x] Loan Products
- [x] Savings Products
- [x] Share Products
- [x] Fixed Deposit Product
- [x] Recurring Deposit Product
- [x] Charges
- [x] Manage Offices
- [x] Manage Employees
- [x] Provisioning Criteria
- [x] Teller/Cash Management
- [x] Manage Data Tables
- [x] Manage Codes
- [x] View Roles
- [x] Manage Hooks
- [x] Manage Reports
- [x] All Reports
- [x] Global Configurations
- [x] Users
- [x] Chart of Accounts

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by wkk91193** [comment]
@ankit01ojha @mbj36 @gkrishnan724   This merge inflicts bugs. To reproduce try returning to the particular page where pagination was applied after browsing to other pages, then pagination does not work.  [Fineract -617](https://issues.apache.org/jira/browse/FINERACT-617)

**Comment by ankit01ojha** [comment]
@wkk91193, Thank for reporting the issue, I will try to fix this ASAP.

**Comment by wkk91193** [comment]
@ankit01ojha  we're eagerly anticipating a fix.Any update on this?It's blocker  since we can't scroll through the paginated list

**Comment by ankit01ojha** [comment]
@wkk91193 , I am trying to fix this issue. This issue is happening only in particular case i.e. when you go the clients' page and then you go to any of above-listed places or from the above-listed places you go to clients' and then come back, the pagination stops working. Pagination is working fine even if leave the "all reports" page to go to any other page(except for clients') and then come back to "all reports" page

**Comment by ankit01ojha** [comment]
@wkk91193 sorry, for taking this long to fix this issue. I guess it will get fixed after this PR(#2943 ) gets merged :)

**Comment by wkk91193** [comment]
@ankit01ojha  Thanks Ankit! That's good news

**Pull request merged**
