### PR TITLE
Fixed Client address fields not showing

### PR DESCRIPTION
**Pull request by BLasan**
## Description
See #3336 

## Related issues and discussion
#3336 

## Screenshots, if any
Screenshot from 2021-01-28 02-12-58

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@bharathcgowda @spider0061 Please review and merge

**Review by spider0061 — COMMENTED** [review]
Screenshot from 2021-02-05 23-04-00
@BLasan Can you please again verify the changes as client's address field for me is not visible. Which server did you use for testing?

**Comment by BLasan** [comment]
> Screenshot from 2021-02-05 23-04-00
> @BLasan Can you please again verify the changes as client's address field for me is not visible. Which server did you use for testing?

This is for fineract server. For the dev.mifos.io it worked. @bharathcgowda sir also tested that for dev.mifos.io. Isn't it working now?

**Comment by BLasan** [comment]
@spider0061 You need to enable the address field first, and then you can try testing these changes. But you won't be able to submit. That issue has been address by the PR #3344

**Review by spider0061 — APPROVED** [review]

**Comment by bharathcgowda** [comment]
@edcable can we get this merged by someone, or could I merge it as it is already being approved by @spider0061

**Review by wkk91193 — APPROVED** [review]

**Comment by bharathcgowda** [comment]
merging the PRs as it is reviewed and approved

**Pull request merged**
