### PR TITLE
MIFOSX-2404: Add Date of Issuance as Mandatory Field for Client Identifier

### PR DESCRIPTION
**Pull request by HiroIshikawa**
Hello all,

I implemented the user interface for the Date of Issuance field as mandatory field for adding client identifier page. I appreciate for your review and advises on fixes and improvements.

JIRA issues link: [](https://mifosforge.jira.com/browse/MIFOSX-2404)

Screenshot for the user interface:
mifos_2404_1

### CODE REVIEW

**Comment by rajuan** [comment]
dateOfIssuance field is not supported in the backend platform. There is no use of sending this field from UI when it is not getting persisted.

**Comment by HiroIshikawa** [comment]
@rajuan, thank you for your commenting and sorry that I could not support the backend. 

Since I am a new to contribute to this project and an open source project in general, I am glad if I can get guidance on how to commit a corresponding backend change along with a UI change like this case. 

So to complete the issue, how should I commit the UI change and backend change at the same time? Should I make two different PRs to backend codebase and front-end codebase under the same issue id and clarify that I am PRing these at the same time in the comment space (putting the link of PR each other etc..)?

I appreciate if I can get any advice from you.

**Comment by rajuan** [comment]
@HiroIshikawa You are right... you can send 2 PRs for the same issue... one on GitHub.com/apache/incubator-fineract and another on GitHub.com/openmf/community-app

**Comment by HiroIshikawa** [comment]
@rajuan I understood. I will retry sending 2 PRs next time.
Thank you so much for your answer..!

**Pull request closed without merging**
