### PR TITLE
Fixed Date For Safari

### PR DESCRIPTION
**Pull request by maektwain**
## Description
Fixed the date null value in the UI for safari .

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by maektwain** [comment]
Could we merge this asap? Its a small fix.   @santoshconflux I just tagged you since I don't know who helps merging the code.
Thanks

**Comment by awasum** [comment]
I will be merging this without testing. But I hope this change does not break this feature for other browsers.

**Comment by francisguchie** [comment]
This fix creates transaction dates to appear as null 
All transaction dates on Products and Accounting Transactions

**Comment by francisguchie** [comment]
@awasum  please let us revisit this fix

**Comment by awasum** [comment]
Ok..I am merging your fix to this issue @francisguchie

**Pull request merged**
