### PR TITLE
Fix #3327 - Edit share product

### LINKED ISSUE #3327: Unable to Edit the Shares Product
Unable to Modify the already created shares product. Submit button is not working

You can try out here:
https://openmf.github.io/community-app/?baseApiUrl=https%3A%2F%2Fdemo.fineract.dev&tenantIdentifier=default#/editshareproduct/2

issue

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Fixed the issue in Edit Share Product component. 

## Related issues and discussion
#3327 (Issue)
#3329 (PR)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@bharathcgowda Please review. And shall I close the PR #3329 due to inactivity sir?

**Comment by bharathcgowda** [comment]
@BLasan  if the PR is merged and the issue is fixed, then you can close it.

**Comment by BLasan** [comment]
> @BLasan if the PR is merged and the issue is fixed, then you can close it.

Yes sir. He has already closed the PR. And the relevant issue gets fixed properly from these changes. I've given him the co-authorship for this commit

**Comment by bharathcgowda** [comment]
closing this on confirmation from @BLasan

**Pull request closed without merging**
