### PR TITLE
fixed issue #1778

### PR DESCRIPTION
**Pull request by Anh3h**

### CODE REVIEW

**Comment by mbj36** [comment]
@Anh3h This is not a good fix, you are making so many changes to css file.

Suggestion would be rebase your branch and send PR again with minimum changes

**Comment by Anh3h** [comment]
Sorry was not online yesterday. The issue relating to this pull request is a style issue so to fix it I needed to add some css code. I don't understand please

**Comment by mbj36** [comment]
You don't need to make changes in css files, you have to make changes in scss files which is inside styles-dev/main/components . styles.css is auto-generated when u run the command `sass styles.scss > ../../styles.css` inside main folder

**Comment by Anh3h** [comment]
Ok

**Comment by Anh3h** [comment]
i updated the fix for this issue. after writing the scss code for the styling am i to update a style.css and include in my PR

**Pull request closed without merging**
