### PR TITLE
Reskin: Fix #2102 - Drop-down menu of Add Charge for savings account is showing invalid c…

### LINKED ISSUE #2102: Reskin: Drop-down menu of  'Add Charge' for Savings Account is showing invalid characters
>Create any Saving product and any Savings Charge
>Go to client page, and click on 'New Saving'. Enter the inputs and submit it. 
>Click on 'Add Charge' and observe the drop-down menu.

reskin

Same thing happen even you try to add charge after approving the saving account and also adding Client Charge

### PR DESCRIPTION
**Pull request by iamsk9**
…haracters

Resolved the problem of Add charge for saving account is showing invalid characters.

Before Changes:

269ca5e4-0970-11e7-974c-ee8b3ac39e87

After Changes

screenshot 24

### CODE REVIEW

**Comment by iamsk9** [comment]
@mbj36 Made changes to the drop-down of adding client charge. Please review it.

**Comment by mbj36** [comment]
@iamsk9 squash your commits

**Comment by mbj36** [comment]
@iamsk9 Any updates ?

**Comment by mbj36** [comment]
Fixed

**Pull request closed without merging**
