### PR TITLE
Fix #2888 Incorrect Placement of Tooltips

### LINKED ISSUE #2888: Incorrect placement of Tooltips in some places of the app
## Description
On hovering over the question mark icon at some places in the app, the tooltip (message) is displayed at an incorrect place. The following is a list of those places:
- [x] Create Share Product
- [x] Edit Share Product
- [x] Create Savings Product
- [x] Edit Savings Product
- [x] Create Loan Product (Accounting)
- [x] Edit Loan Product (Accounting)
- [x] Create Fixed Deposit Product (Settings, Accounting)
- [x] Edit Fixed Deposit Product (Settings, Accounting)
- [x] Create Recurring Deposit Product (Settings, Accounting)
- [x] Edit Recurring Deposit Product (Settings, Accounting)

Also, tooltip hasn't been updated to uib-tooltip in the Accounting Section of Fixed Deposit Products.

## Steps to Reproduce
Admin -> Products -> Share Products -> Create Share Product
Admin -> Products -> Share Products -> Click any product -> Edit
Admin -> Products -> Savings Products -> Create Savings product
Admin -> Products -> Savings Products -> Click any product -> Edit
Admin -> Products -> Loan Products -> Create Loan product
Admin -> Products -> Loan Products -> Click any product -> Edit
Admin -> Products -> Fixed Deposit Products -> Create Fixed Deposit product
Admin -> Products -> Fixed Deposit Products -> Click any product -> Edit
Admin -> Products -> Recurring Deposit Products -> Create Recurring Deposit product
Admin -> Products -> Recurring Deposit Products -> Click any product -> Edit

After each of the following, hover over any question mark icon

## Expected Behaviour
The tooltip should be visible directly on the icon and not away from it when the mouse hovers over it.

## Actual Behaviour
The tooltip placement is away from the icon when the mouse hovers over it.

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Google Chrome

## Screenshots, if any
screenshot 312
screenshot 295
screenshot 297
screenshot 299
screenshot 311
screenshot 298
screenshot 300
screenshot 313
screenshot 314
screenshot 315

### PR DESCRIPTION
**Pull request by abhaychawla**
## Description
Tooltip message is now correctly placed when visible while mouse hovers over the question mark icon.
The following is a list of those places in the app which were updated:
- [x] Create Share Product
- [x] Edit Share Product
- [x] Create Savings Product
- [x] Edit Savings Product
- [x] Create Loan Product (Accounting)
- [x] Edit Loan Product (Accounting)
- [x] Create Fixed Deposit Product (Settings, Accounting)
- [x] Edit Fixed Deposit Product (Settings, Accounting)
- [x] Create Recurring Deposit Product (Settings, Accounting)
- [x] Edit Recurring Deposit Product (Settings, Accounting)

Also, tooltip has been updated to uib-tooltip in the Accounting Section of Fixed Deposit Products.

## Related issues and discussion
#2880  

## Screenshots, if any
screenshot 318
screenshot 319
screenshot 320
screenshot 321
screenshot 322
screenshot 323
screenshot 324
screenshot 325
screenshot 326
screenshot 327

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by ShruthiRajaram** [comment]
@abhaychawla changes look good. But can you please resolve conflicts ?. I will approve after that.

**Comment by abhaychawla** [comment]
@ShruthiRajaram sorry for the delay. I resolved the conflicts. I am not sure if I did this right. Let me know.

**Comment by ShruthiRajaram** [comment]
@abhaychawla thanks for resending the PR. But I think there is  a rebase issue. It says 103 commits and 273 file changes. Kindly check..

**Comment by abhaychawla** [comment]
@ShruthiRajaram Fixed!

**Comment by ShruthiRajaram** [comment]
@mbj36  kindly merge this PR

**Pull request merged**
