### PR TITLE
Reskin : Fix #2002 - Large gap between field name and its corresponding radio button

### LINKED ISSUE #2002: Reskin: Large gap between Field Name and it's corresponding radio button
Check the screenshots for some of the cases:

reskin

reskin1

reskin2

### PR DESCRIPTION
**Pull request by MexinaD**

### CODE REVIEW

**Comment by mbj36** [comment]
Please mention here in checklist in which pages you have solved the probem. It would be easy to review then

**Comment by MexinaD** [comment]
Problem solved on the page of creating loan product, saving product, share product, F.D product, R.D product and creating loan account.

**Comment by mbj36** [comment]
Hello @MexinaD You have made lots of changes in lines of code which has no meaning with actual issue. I would suggest you to please rebase your branch with current new_reskin branch and then send the PR with proper description of the changed behaviour, i find it difficult to review. Ping me on gitter for further help

Thanks for your understanding

**Comment by MexinaD** [comment]
I understand you, let me do that

**Pull request closed without merging**
