### PR TITLE
GLIM_GSIM_UI

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description
UI of GLIM_GSIM module. 

## Related issues and discussion
#https://jira.apache.org/jira/browse/FINERACT-603

### CODE REVIEW

**Comment by awasum** [comment]
@nikpawar  and @francisguchie does this look good to you? will you want to merge it?

**Comment by francisguchie** [comment]
@awasum  and @nikpawar  let me look at it before i can comment.

**Comment by nikpawar89** [comment]
I did not review this PR, will take a look.

**Comment by francisguchie** [comment]
@rrpawar96 , @awasum @nikpawar 
My findings on the GSIM 
GSIM Application, Approval and Activation of the child accounts is all good
GSIM Deposit is ok  

My Findinds on the GLIM
GLIM application 
During application i can not navigate back to the group
image

**GLIM Approval**
during approval, navigation back to group is available but the clients' names are missing but once user clicks approve, they appear  the api is  /viewglimaccount/?/?
image
Names appear a
image

**GLIM Disbursement**
Names do no appear just like for approval and the api is  **/viewglimaccount/?/{{glim_account_number}}**
image

**api = /glimloanaccount/{{glim_account_number}}/glimDisburse/?**
The names appear
image


**Functionally**
The GSIM application, approval, activation and Deposits all work well 
The GLIM application, approval, activation and repayment all work well 

**Graphically** 
the api  /viewglimaccount/?/{{glim_account_number}} needs to be looked into

**Comment by rrpawar96** [comment]
@francisguchie,  thanks for performing functional testing, will make the required changes in the PR and will update soon.

**Comment by francisguchie** [comment]
welcome @rrpawar96

**Comment by rrpawar96** [comment]
@francisguchie, The comments have been addressed and made some changes in the viewglimaccount-page table and added navigation in the GLIM.

**Comment by awasum** [comment]
> @francisguchie, The comments have been addressed and made some changes in the viewglimaccount-page table and added navigation in the GLIM.

@francisguchie, have your comments been addressed. Just indicate so we can merge this PR.

**Comment by francisguchie** [comment]
@awasum 
i am going to respond by COB 20th August 2020 (GMT)

**Comment by francisguchie** [comment]
@rrpawar96  and @awasum 

I have seen a good number of  issues raised answered, i have observed some improvements too like the load status 
However, the following need to be addressed 

1 - Wrong client IDs and missing client names at viewing of Glimloan view -- GLIM Loan approval and Disbursal is all ok
image

2- The group display is showing gsim id and glim id  but not the gsim / glim account_number
image

**Comment by awasum** [comment]
> @rrpawar96 and @awasum
> 
> I have seen a good number of issues raised answered, i have observed some improvements too like the load status
> However, the following need to be addressed
> 
> 1 - Wrong client IDs and missing client names at viewing of Glimloan view -- GLIM Loan approval and Disbursal is all ok
> image
> 
> 2- The group display is showing gsim id and glim id but not the gsim / glim account_number
> image

@rrpawar96 Did you see this feedback from Francis? Will you like to address this?

**Comment by rrpawar96** [comment]
@awasum , Yes I am going to address the comments of @francisguchie soon, and will give the update on it.

**Comment by rrpawar96** [comment]
@francisguchie , @awasum The comments have been addressed and PR is been updated.

**Comment by edcable** [comment]
Thanks @rrpawar96. @francisguchie @bharathcgowda could you do one last functional review? @rrpawar96 there is one last merge conflict to address as well.

**Comment by rrpawar96** [comment]
@edcable, yes the merge conflict has been resolved.

**Comment by francisguchie** [comment]
> Thanks @rrpawar96. @francisguchie @bharathcgowda could you do one last functional review? @rrpawar96 there is one last merge conflict to address as well.

@rrpawar96 

I have seen the changes, all issues addressed and a few additions (these make it easy for a new user to enjoy the GLIM / GSIM loaning method more easily )

Image below speaks the summary 

image

**Comment by bharathcgowda** [comment]
@francisguchie @edcable looks good to me. one flow tested and working fine.

**Pull request merged**
