### PR TITLE
fix #2740 - Date of Birth of client cannot be edited to the previous date in client

### LINKED ISSUE #2740: Date of Birth of client cannot be edited to the previous date in client
## Description
Date of Birth of client cannot be edited to the previous date in client

## Steps to Reproduce
Client -> Choose any client -> Edit -> Change date of birth to previous date(cannot do)

## Expected Behaviour
Should be able to change to the previous date
## Actual Behaviour
Cannot edit

## Settings
- Mifos X version: 
- Browser used: Chrome

### PR DESCRIPTION
**Pull request by anweshknayak**
## Description
Date of Birth of client can be edited to the previous date in client

## Related issues and discussion
#2740 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by anweshknayak** [comment]
@gkrishnan724 its working fine on my end

**Comment by anweshknayak** [comment]
@gkrishnan724 so should I close this one?  merged in #2744

**Comment by anweshknayak** [comment]
similar to #2744 should work fine @gkrishnan724

**Comment by gkrishnan724** [comment]
Has been fixed in #2744, so closing this, thanks for the contribution.

**Comment by anweshknayak** [comment]
@gkrishnan724 those are two different files. Mine is for edit view. Please recheck

**Comment by anweshknayak** [comment]
Also that was marked duplicate already. Don't understand why it was merged before this.

**Comment by gkrishnan724** [comment]
Sorry about that @anweshknayak  didn't notice.

**Pull request merged**
