### PR TITLE
MifosX issue 2112 : Dashboard Label not working properly

### PR DESCRIPTION
**Pull request by rohan1309**
Key of scope, in disbursed pie data was incorrectly labeled.

### CODE REVIEW

**Comment by rohan1309** [comment]
Misplaced Key in commit b5f98c0.

**Comment by vishwasbabu** [comment]
@rohan1309 : Can you please squash your commits into a single commit ?

**Comment by rohan1309** [comment]
Yeah, the commit b5f98c0 was incorrect. Can I revert that instead?

**Comment by vishwasbabu** [comment]
sure, I'll close off this pull request and you can send a new one...

**Pull request closed without merging**
