### PR TITLE
 fix #1659-print screen doesn't work

### LINKED ISSUE #1659: Print Screen (CTRL+P) doesn't work
For both the old skin and the re-skin, CTRL+P doesn't work.

On the old skin, just a blank page is displayed
On the new skins, the layout and CSS is all wonky.

See screenshot. 
screen shot 2016-11-22 at 4 13 19 pm

### PR DESCRIPTION
**Pull request by muddlebee**
## Description
minor fix to print screen css. alligned properly now.

## Related issues and discussion
#1659 

## Screenshots, if any
screenshot from 2018-01-05 15 42 15

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by alexnavis** [comment]
@anweshknayak Will it possible for you to resolve the conflicts ?. Kindly let me know.

**Comment by luckyman20** [comment]
@anweshknayak Please squash your commits and resolve the merge conflicts.

**Comment by edcable** [comment]
@alexnavis @luckyman20 I don't believe @anweshknayak is still active in our community. Are either of you able to address the merge conflicts?

**Comment by luckyman20** [comment]
@edcable There had been a lot of changes in the `styles.css` file since @anweshknayak made this PR, and I am afraid if while resolving merge conflicts, we might break something else, I would suggest that we make a new PR for the same issue and keep in mind that it doesn't break anything else.

Any volunteer with good CSS knowledge should be able to do it.

**Comment by rchtgpt** [comment]
@edcable, I have resolved the merge conflicts! 😄

**Pull request closed without merging**
