### PR TITLE
holiday-table-overflow-fixed

### PR DESCRIPTION
**Pull request by Jov03**
## Description
Table was placed in a row whose all 12 columns were occupied by div so in order to fix this i moved the table out of the row.

## Related issues and discussion
#2785 

## Screenshots
screen shot 2018-01-08 at 2 44 40 pm

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by abhaychawla** [comment]
@Jov03 Please resolve the conflicts so that changes can be approved and merged.

**Comment by Jov03** [comment]
@abhaychawla i have resolved the conflicts.

**Comment by abhaychawla** [comment]
@mbj36 @gauravsaini03 Please merge this PR.

**Pull request merged**
