### PR TITLE
Resolving missing icons for tabs issue #2130

### PR DESCRIPTION
**Pull request by ThisuraThejith**
Resolved the problem of missing icons in the client general tab.

### CODE REVIEW

**Comment by ThisuraThejith** [comment]
@mbj36 Please review this and merge.

**Comment by mbj36** [comment]
selection_025

**Comment by ThisuraThejith** [comment]
Updated PR. Now it shows drop down as follow.
fix

**Comment by mbj36** [comment]
Thanks @ThisuraThejith

**Comment by ThisuraThejith** [comment]
Thanks @mbj36 for the great support get my hands on with openmf.

**Pull request merged**
