### PR TITLE
Fixed Alignment of Office Options on the right side along with filter options

### PR DESCRIPTION
**Pull request by richardli314**
Changed HTML/CSS

### CODE REVIEW

**Comment by nazeer1100126** [comment]
Can you please add Jira issue number with this PR

**Comment by richardli314** [comment]
@nazeer1100126 I have looked through Jira and Github for the issue number, but I could not find it. Is there another way I could locate it?

**Comment by mbj36** [comment]
@nazeer1100126  this issue was directly mentioned in GCI dashboard by saransh. Here is the GCI issue link  - https://codein.withgoogle.com/dashboard/task-instances/5068236783616000/

**Comment by nazeer1100126** [comment]
I think you are trying to achieve moving select next to filter input. Can't we do with col-sm or col-md? Why do we need to modify bootstrap-ext.css and add new class? if you want 0 border then add if required.

**Pull request closed without merging**
