### PR TITLE
adds the meaningful label against the button "Activate Self Service User"

### PR DESCRIPTION
**Pull request by OHassini**
## Description
Added meaningful tool tip for help link in 'Create Self user page' .

## Related issues and discussion
#3139 

## Screenshots, if any
Capture d’écran (164)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by jonathanzhang53** [comment]
This technically works, but is not the right way to relabel the tooltip. If you check the other lines in the file, all of them use labels which refer to translations that load in. This ensures that you can view the website in whatever language you want. So here, you need to look into the global translations folder and add it to the english translations

I believe you do not need to provide anything for the other languages...

**Comment by abhaychawla** [comment]
Hi @OussEmaDevCode, also please ensure that you create a separate branch to make you changes instead of making them directly in the develop branch. Follow the steps specified here: https://github.com/openMF/community-app/blob/develop/Contributing.md 
Close this PR and resend it after making the required changes in a separate branch. Make sure you commit message is also a bit more descriptive. Feel free to ask questions, if you have any.

**Review by abhaychawla — CHANGES_REQUESTED** [review]
Hi @OussEmaDevCode, also please ensure that you create a separate branch to make you changes instead of making them directly in the develop branch. Follow the steps specified here: https://github.com/openMF/community-app/blob/develop/Contributing.md
Close this PR and resend it after making the required changes (as specified by Jonathan) in a separate branch. Make sure your commit message is also a bit more descriptive and as per the guidelines in CONTRIBUTING.md
Feel free to ask questions, if you have any.

**Comment by OHassini** [comment]
Hi again , I am really sorry for not giving that much importance to CONTRIBUTING.md considering how essential it is , anyway here's the new pull request [link](https://github.com/openMF/community-app/pull/3151), and thank you

**Pull request closed without merging**
