### PR TITLE
No Validations for username and password length while creating self-s…

### PR DESCRIPTION
**Pull request by nnatarajan**
…ervice user #3136

@wkk91193 , I manually changed the locale-en.json file in include the message. Please let me know the correct way to update the json.

@Sanyam96 @rahulg963 , Can you advise on this?

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by wkk91193** [comment]
@nnatarajan Code looks good to me. @edcable Since I'm not granted merge privileges could you take the next steps to merge this please?

**Comment by nnatarajan** [comment]
@wkk91193 , I wanted to confirm that you read my note above the description? Ok to manually change the json? I see that there is a translator program for the json file. I am not sure how this works?

**Comment by wkk91193** [comment]
@nnatarajan Yes, I did read that. It is okay for now. As I understand, given a locale configuration in the setting, the translator would lookup matches in all locale language json files. Ideally, these json files need to sync up, but that's another task in itself.
@edcable Is there any relevant person with translation expertise to help to sync up the changes?

**Comment by nnatarajan** [comment]
@wkk91193 , I am getting the same network error as PR #3254 . It seems that I might get this same error for all of my PRs. Perhaps it is an error in the test itself?

From Ed's email, I gather @ankit01ojha be will assisting with Community App PR reviews.

**Comment by nnatarajan** [comment]
@wkk91193 , thanks for the okaying this one. I can merge this. Should I select the option for rebase and merge?

**Pull request merged**
