### PR TITLE
Fix #2097 - Make design for new applications the same

### LINKED ISSUE #2097: Designs should be same for New Loan/Saving/Share/FD/RD applications
Currently on reskin, you can see different designs, placing of 'Cancel' buttons:

reskin1

reskin2

reskin3

reskin4

reskin5

### PR DESCRIPTION
**Pull request by AkashBhave**
## Description
The design for creating a new **Loan**/**Saving**/**Share**/**Fixed deposit**/**Recurring deposit** application has been made coherent. The padding for each element has been set to the same across all applications, as well as the table size.

The general layout for **Fixed deposit** and **Recurring deposit** applications has also been made the same. The reason that there is only a "Cancel" button at the bottom (and not "Previous" and "Next") is because these applications don't utilize the multi-tab layout. 

All of the files have also been reformatted, so that the code is easier to read and debug.

## Screenshots
New loan account (`app/views/loans/newloanaccount.html`): 
loan
New savings account (`app/views/savings/new_saving_account_application.html`):
saving
New share account (`app/views/shares/createshareaccount.html`):
shares
New fixed deposit account (`app/views/deposits/fixed/newapplication.html`):
fd
New recurring deposit account (`app/views/deposits/recurring/newapplication.html`):
rd

<hr>
Part of a task for Google Code-in 2017. 🥇

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@AkashBhave Noticed the submitted on field went out of the card in new savings, could you please take a look into it?

**Comment by AkashBhave** [comment]
@gkrishnan724 Thanks for pointing that out. I have updated my pull request to fix this issue.

**Comment by AkashBhave** [comment]
@gkrishnan724 Updated PR with changes. I initially couldn't get the "Fund" drop-down menu to stay in the container, but then I realized that setting a `max-width` property to the element would limit the size. This fixed the issue of the fields being too close together and the fund going outside the container.

**Comment by AkashBhave** [comment]
@gkrishnan724 Interesting, it doesn't look like that on my end.
image

**Comment by AkashBhave** [comment]
@gkrishnan724 I updated my pull request anyways, even though it was working for me before. I simply added `left:0;` to the `style` attributes of the "Fund" drop-down element. If it still doesn't work on your end, I'm stumped. ❓

**Comment by gkrishnan724** [comment]
@AkashBhave what is the zoom percentage of your browser? I guess it is lesser than 100% in your case when I decreased the zoom, it worked fine. But when it is 100% the dropdown moves.

**Comment by AkashBhave** [comment]
@gkrishnan724 The zoom percentage on my browser is 100%. It is being displayed on a 19", 1080p screen. When I increase the zoom to 125%, I get the same problem that you get. However, I don't think that this is an issue specifically regarding our code. It probably has to do with HTML and browser rendering, in order to utilize all the space on the screen.

**Comment by gkrishnan724** [comment]
We could look into this issue, later on, I'll approve the task since the rest looks good

Thanks !

CC - @mbj36  could you please verify this issue?

**Comment by Agnessy** [comment]
Hi @gkrishnan724 @AkashBhave I think the that fund issue relates with 
https://github.com/openMF/community-app/issues/2668

**Comment by Agnessy** [comment]
Hi @gkrishnan724 @AkashBhave I think the that fund issue relates with 
https://github.com/openMF/community-app/issues/2668

**Comment by AkashBhave** [comment]
@Agnessy Once this pull request is merged, the fund issue can be closed, since this PR fixes it.

**Pull request merged**
