### PR TITLE
MIFOSX-2327 issue. Does not come back to group, when cancel transfer clients.

### PR DESCRIPTION
**Pull request by dtsuran**

### CODE REVIEW

**Comment by rajuan** [comment]
new PR received

**Comment by dtsuran** [comment]
I don't understand. What is problem?

**Comment by rajuan** [comment]
Sorry, there was another latest pull request for the same issue. I didn't realise it was from different contributor. I will get this reviewed tomorrow.

**Comment by rajuan** [comment]
thanks

**Pull request merged**
