### PR TITLE
ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by luphieanza**
UPDATE for Create a How-To Guide On Submitting A Bug Report in GitHub Issues GCI2017 TASK - Muhammad Rafly Andrianza

<h1>When submitting a new issue, please fill in :</h1>

## Title
Give the title as interesting and appropriate as your issue

## Description
Fill in descriptions as much as possible and is good value for others

## Steps
Include detailed steps to reproduce the issue.

## Others Support Materials
Provide:
- Screenshots
- Log files
- URLs or references for the report you submit.

## Requirements
- Mifos X Version
- Browser
- Platform / OS Version

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by luphieanza** [comment]
pardon, a PR for GCI2017 Task (Create a How-To Guide On Submitting A Bug Report in GitHub Issues)
and I am still waiting for the previous assignment to have been reviewed, Regards.

**Comment by ankit01ojha** [comment]
@luphieanza , There is already a merged PR for this https://github.com/openMF/community-app/pull/2664

**Comment by mbj36** [comment]
This has been already merged

**Pull request closed without merging**
