### PR TITLE
Fix #3308: Fixed savings account dropdown in client new share account page

### LINKED ISSUE #3308: Can't select Default Savings Account when Creating New Share Account
## Navigate to any client with an active savings account, select New Share Account.

On the terms page, I am unable to select a savings account from drop down menu even if there's an active savings account for that member. 

It should display a list of savings accounts for that member that could be selected. 
Screenshot 2020-09-22 at 4 42 21 PM

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Fixed options for active savings account field in client->new share account page.

## Related issues and discussion
#3308 

## Screenshots, if any
Screenshot from 2020-10-31 21-01-35

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@spider0061 Please review this.

**Review by spider0061 — DISMISSED** [review]
Nice Work! @BLasan

**Comment by BLasan** [comment]
@spider0061 I added some changes. Please review :)

**Comment by spider0061** [comment]
@bharathcgowda @edcable Sir can you test it? I am not able to create share account. Seems to be a backend problem.

**Comment by bharathcgowda** [comment]
This issue is fixed on the latest code base, and I was able to create the shares account.
I think we can close this ticket and PR as it is working as expected on the latest develop codebase.

image

**Comment by BLasan** [comment]
> This issue is fixed on the latest code base, and I was able to create the shares account.
> I think we can close this ticket and PR as it is working as expected on the latest develop codebase.
> 
> image

No problem sir if it works fine  :)

**Comment by bharathcgowda** [comment]
closed this issue, as the feature is working as expected.
Thanks @BLasan

**Pull request closed without merging**
