### PR TITLE
Initial version of adhocquery UI

### PR DESCRIPTION
**Pull request by iamrupok**
Initial version of adhocquery ui

### CODE REVIEW

**Comment by iamrupok** [comment]
can some one please take care of this PR

**Comment by iamrupok** [comment]
@mbj36 please review the PR

**Comment by mbj36** [comment]
@iamrupok  We are not accepting any changes in develop branch, please post detail issue to get your PR reviewed and create PR on new_reskin branch

**Comment by iamrupok** [comment]
when i try to fork the new_reskin branch it take me to develope branch?what
could be the issue can you pleae provide me some hints about it.

**Comment by mbj36** [comment]
You need to do `git checkout new_reskin` and then run these command again `bower install` and `npm install`

**Pull request closed without merging**
