### PR TITLE
Adhoc query UI

### PR DESCRIPTION
**Pull request by iamrupok**

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@iamrupok why do we need to add English translations in other locale files?

**Comment by iamrupok** [comment]
If anyone try to use this in other local the UI will break it it does not
get the value from those local file

**Comment by nazeer1100126** [comment]
@iamrupok It won't give any problem. If translation is not present it will show error code only.
Somebody has to make these proper translations according the different languages.

**Comment by iamrupok** [comment]
it would not be a problem if it stays there.some one can change the value
easily.as the key is already there.otherwise someone have to find the keys
that is used for the proper translation dont you think so

**Comment by nazeer1100126** [comment]
@iamrupok usually, we will try to add the missing keys. I don't suggest adding English translations in other language locale files. Please remove them.

**Comment by iamrupok** [comment]
ok

**Comment by iamrupok** [comment]
this is really a

**Pull request closed without merging**
