### PR TITLE
Fix #2820-Update fontawesome version and correct improper buttons

### LINKED ISSUE #2820: Icons missing from delete/edit buttons in multiple pages
## Description
Icons are missing from buttons(mostly from delete but a few edit also).

## Steps to Reproduce
A list of pages that have buttons without icons that I found till now.
1. Accounting: chart of accounts, closing entries, accounting rules 

2. System: manage data table, manage roles and permissions, manage hooks, manage reports, scheduler jobs, configurations 

3. Products: charges, products mix

4. Templates

5. Organization: manage holidays, loan provisioning criteria

## Expected Behaviour
Buttons should have appropriate icons.

## Settings
- Mifos X version: 17.07.01
- Browser used: Firefox

### PR DESCRIPTION
**Pull request by shubhshrma**
## Description
1. Used latest font-awesome version because the ```fa-trash``` icon was not working due to a bug in the older version. This icon is used in many delete buttons in the website and all of them were not showing due to older version.

2. Changed three other wrongly used icons to correct icons.

## Related issues and discussion
#2820 

## Screenshots, if any
screenshot from 2018-01-20 01-53-26
screenshot from 2018-01-20 02-18-04
screenshot from 2018-01-20 02-18-30

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
CC - @mbj36

**Comment by muskankhedia** [comment]
@Nayan Sir, I was looking for this PR, and the issue related to it, and all the icons in the webpages as mentioned in the PR and issue are presently working fine. According to me, this PR can be closed as any such update is not required presently and all the icons are working fine.

**Comment by edcable** [comment]
@santoshconflux Can you please confirm that this has already been fixed and that we can close this PR. Otherwise I will request @shubhshrma to address the merge conflicts.

**Comment by edcable** [comment]
Already fixed.

**Pull request closed without merging**
