### PR TITLE
FINERACT-1663:fixed-reports-overlapping

### PR DESCRIPTION
**Pull request by rrpawar96**
https://issues.apache.org/jira/browse/FINERACT-1663

image

### CODE REVIEW

**Comment by francisguchie** [comment]
@rrpawar96  this is good work

**Comment by francisguchie** [comment]
@awasum  @bharathc27  this issue has been solved i am using it already in production

**Comment by ikimbra** [comment]
The issue is solved, table reports are no longer collapsing headers. @awasum I propose you look at it. 
Thank you @rrpawar96

**Comment by eroemma** [comment]
This is amazing @rrpawar96 Well done.

**Comment by rrpawar96** [comment]
@luckyman20, This PR has been tested, Please help us to review this PR.

**Comment by luckyman20** [comment]
@rrpawar96 Good work.

**Pull request merged**
