### PR TITLE
Fix for 'Submit' button is not working on Upload Client Document Page #2133

### PR DESCRIPTION
**Pull request by ThisuraThejith**
Added upload change directive to fix file uploading issue.

### CODE REVIEW

**Comment by ThisuraThejith** [comment]
@mbj36 Kindly let me know whether this approach is correct.

**Comment by ThisuraThejith** [comment]
@mbj36 @santoshmath Kindly review the PR and check whether the issue is resolved.

**Comment by mbj36** [comment]
@nazeer1100126 I am not sure about this approach. Can you please review it ?

**Comment by avikganguly01** [comment]
@ThisuraThejith 
In essence, approach is not incorrect. 👍 

But I believe there is already a standard directive somewhere in the libraries/directives folder named ng-file-select (probably not nv-file-select, maybe it was a typo). I would strongly suggest not creating custom directives when there are globally accepted standard directives out there. If you are unable to find the directive in the codebase, please consider including https://github.com/danialfarid/ng-file-upload as a dependency and use ng-file-upload to populate the $files variable.

+1 for the effort though.

@mbj36 Let me know if above suggestion makes sense as I don't know which directive the community app is using for all standard file uploads. I have had some good experiences in using/building features on top of the ng-file-upload directive (link shared above).

**Comment by ThisuraThejith** [comment]
@avikganguly01 thanks for the review. Will do the needfull.

**Comment by mbj36** [comment]
@ThisuraThejith Can you reslove conflicts and send PR ? I will merge this one

**Comment by ThisuraThejith** [comment]
@mbj36 I will do it EOD tomorrow.

**Comment by Anh3h** [comment]
@mbj36 @ThisuraThejith 
Same issue for loan document upload. The is no need to create a new directive just ```nv-file-select``` to ```ngf-select``` at the file will upload.
But even after the file uploads I still get a 500 error
I don't know if it's backend error something

**Comment by mbj36** [comment]
@ThisuraThejith Please look on this PR - https://github.com/openMF/community-app/pull/2270

No need to create a new directive, i am closing this PR  

@Anh3h Would you like to send PR for this issue ?

**Comment by Anh3h** [comment]
Yes

**Comment by mbj36** [comment]
Go Ahead

**Pull request closed without merging**
