### PR TITLE
Fix for MIFOSX-2627

### PR DESCRIPTION
**Pull request by gkrishnan724**
Issue:
Proper error messages were not displaying in making datatable entry
Fix:
Added api-validate directive which would display proper error message

### CODE REVIEW

**Comment by nazeer1100126** [comment]
Modifying a directive will affect complete project. Have you tested it? 
Don't you think adding <api-validate></api-validate> in makedatatablentry.html is sufficient?

**Comment by gkrishnan724** [comment]
Hi @nazeer1100126 sorry for the late reply, yes, adding the api-validate fixed the issue and I also tested it. Regarding, the modification of the directive all I did is add {{error.field}} which shows in which field the error is present, provided the core returns the field property, if it doesn't return the field property then it will just show the error message like it was before. I added it because the user should know in which field the error is occuring. I do understand that this affects the whole project and yes, I have tested that too. It works fine with all forms.

Test images for current issue:
screenshot from 2016-12-17 18-51-08
screenshot from 2016-12-17 18-55-18
screenshot from 2016-12-17 18-59-36

eg: The edit in the directive is working good in this case(CreateDatatable), as you can see in the console field property of the errorArray is  returned.
screenshot from 2016-12-17 19-19-02

**Comment by nazeer1100126** [comment]
@gkrishnan724 I can see issue with your change
issue

**Comment by gkrishnan724** [comment]
@nazeer1100126  It seems to work fine for me:
screenshot from 2016-12-20 12-17-35

However, I do agree with you since I misunderstood the field property. It seems that it does not return the field name, since in this case it showing "id" which is not the field name. Moreover, I think that when using the app in different languages, name of the field will be different which would cause translation problems. I did not think of that before 

Sorry for the inconvenience I will send a new PR :)

**Pull request closed without merging**
