### PR TITLE
Fix #2350 - Disables previous and next month calendar dates

### LINKED ISSUE #2350: Previous and Next month calendar dates must be dimmed in selected month
For example If you select month as July 2017, in this month June and August month dates should be dimmed. This issue exists with all pop-up calendars in application.

old skin:
demo

reskin:
reskin

### PR DESCRIPTION
**Pull request by OHassini**
## Description
Disabled previous and next month calendar dates on selection of a month in every calendar in the app.

## Related issues and discussion
#2350 

## Screenshots, if any
before:
Clipboard01

after:
Clipboard01

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by abhaychawla** [comment]
Hi @OussEmaDevCode , the issue is to get them disabled/dimmed not remove them from the date picker completely. Please try again. Let us know if you have any questions.

**Review by abhaychawla — CHANGES_REQUESTED** [review]
Working well! Just one more thing you need to ensure, the class muted is being added when the dates are disabled but it doesn't give any `dimmed` effect. Making use of this class, add appropriate CSS so its easy to differentiate disabled dates from those which aren't disabled. (Similar to the screenshot in the issue description.)

**Comment by OHassini** [comment]
@abhaychawla Done !!

**Review by abhaychawla — APPROVED** [review]
Looks good. I have approved @OussEmaDevCode  but could you please change your commit message so that it doesn't show trailing dots in first line. In a commit message, the first line has a character limit and cannot be too long. You can, however, specify a longer description in the body of a commit message if needed. So please shorten the first line ensuring its still descriptive enough and if needed specify description in body. Also, update the title of the PR where also we have `...` before we can merge.

**Comment by OHassini** [comment]
@abhaychawla Done !! It should be good to merge.

**Pull request merged**
