### PR TITLE
Update new notification view and add link from front-end to back-end

### PR DESCRIPTION
**Pull request by Anh3h**

### CODE REVIEW

**Comment by Ippezrobert** [comment]
@Anh3h , Hi Courage, do you get notification at the community-app. Is the community-app notification working or still something has to be fixed. I tried at my side after configuring using this https://mifosforge.jira.com/wiki/spaces/docs/pages/153387033/Configure+Notifications but still not working. Could try at your side and please let me know. @ad-os , Is the community-app side notification working?

**Comment by ad-os** [comment]
Hi @Ippezrobert ,

Please try after this code is merged. It should work after that.

Thanks!

**Comment by Ippezrobert** [comment]
@ad-os , am just testing this PR but am getting error when running grunt clean serve
check error below from web console and community-app doesn't load. please double check this at your side

angular.js:9400 SyntaxError: Unexpected string in JSON at position 330749
    at JSON.parse (<anonymous>)
    at fromJson (http://localhost:9000/bower_components/angular/angular.js:1036:14)
    at defaults.defaults.transformResponse (http://localhost:9000/bower_components/angular/angular.js:6937:18)
    at http://localhost:9000/bower_components/angular/angular.js:6912:12
    at Array.forEach (native)
    at forEach (http://localhost:9000/bower_components/angular/angular.js:303:11)
    at transformData (http://localhost:9000/bower_components/angular/angular.js:6911:3)
    at transformResponse (http://localhost:9000/bower_components/angular/angular.js:7576:17)
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:10930:81)
    at http://localhost:9000/bower_components/angular/angular.js:11016:26
(anonymous) @ angular.js:9400
(anonymous) @ angular.js:6836
wrappedCallback @ angular.js:10933
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
(anonymous) @ angular.js:9400
responseError @ loading-bar.js:135
wrappedErrback @ angular.js:10939
wrappedErrback @ angular.js:10939
(anonymous) @ angular.js:11065
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 TypeError: Cannot read property 'url' of undefined
    at responseError (notificationWidget.js:143)
    at wrappedErrback (angular.js:10939)
    at angular.js:11065
    at Scope.$eval (angular.js:11936)
    at Scope.$digest (angular.js:11762)
    at Scope.$apply (angular.js:12042)
    at done (angular.js:7824)
    at completeRequest (angular.js:8007)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7963)
(anonymous) @ angular.js:9400
(anonymous) @ angular.js:6836
wrappedErrback @ angular.js:10942
(anonymous) @ angular.js:11065
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:7978 XHR finished loading: GET "http://localhost:9000/scripts/config/UIconfig.json".
(anonymous) @ angular.js:7978
sendReq @ angular.js:7800
serverRequest @ angular.js:7534
wrappedCallback @ angular.js:10930
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
(anonymous) @ angular.js:1302
invoke @ angular.js:3708
doBootstrap @ angular.js:1300
bootstrap @ angular.js:1314
(anonymous) @ loader.js:139
execCb @ require.js:1635
check @ require.js:871
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
enable @ require.js:1142
init @ require.js:779
callGetModule @ require.js:1169
completeLoad @ require.js:1549
onScriptLoad @ require.js:1656
angular.js:7978 XHR finished loading: GET "http://localhost:9000/global-translations/locale-en.json".
(anonymous) @ angular.js:7978
sendReq @ angular.js:7800
serverRequest @ angular.js:7534
wrappedCallback @ angular.js:10930
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
(anonymous) @ angular.js:1302
invoke @ angular.js:3708
doBootstrap @ angular.js:1300
bootstrap @ angular.js:1314
(anonymous) @ loader.js:139
execCb @ require.js:1635
check @ require.js:871
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
enable @ require.js:1142
init @ require.js:779
callGetModule @ require.js:1169
completeLoad @ require.js:1549
onScriptLoad @ require.js:1656
angular.js:9400 SyntaxError: Unexpected string in JSON at position 330749
    at JSON.parse (<anonymous>)
    at fromJson (http://localhost:9000/bower_components/angular/angular.js:1036:14)
    at defaults.defaults.transformResponse (http://localhost:9000/bower_components/angular/angular.js:6937:18)
    at http://localhost:9000/bower_components/angular/angular.js:6912:12
    at Array.forEach (native)
    at forEach (http://localhost:9000/bower_components/angular/angular.js:303:11)
    at transformData (http://localhost:9000/bower_components/angular/angular.js:6911:3)
    at transformResponse (http://localhost:9000/bower_components/angular/angular.js:7576:17)
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:10930:81)
    at http://localhost:9000/bower_components/angular/angular.js:11016:26
(anonymous) @ angular.js:9400
(anonymous) @ angular.js:6836
wrappedCallback @ angular.js:10933
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
(anonymous) @ angular.js:9400
responseError @ loading-bar.js:135
wrappedErrback @ angular.js:10939
wrappedErrback @ angular.js:10939
(anonymous) @ angular.js:11065
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 TypeError: Cannot read property 'url' of undefined
    at responseError (notificationWidget.js:143)
    at wrappedErrback (angular.js:10939)
    at angular.js:11065
    at Scope.$eval (angular.js:11936)
    at Scope.$digest (angular.js:11762)
    at Scope.$apply (angular.js:12042)
    at done (angular.js:7824)
    at completeRequest (angular.js:8007)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7963)
(anonymous) @ angular.js:9400
(anonymous) @ angular.js:6836
wrappedErrback @ angular.js:10942
(anonymous) @ angular.js:11065
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:7978 XHR finished loading: GET "http://localhost:9000/global-translations/locale-en.json".
(anonymous) @ angular.js:7978
sendReq @ angular.js:7800
serverRequest @ angular.js:7534
wrappedCallback @ angular.js:10930
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
(anonymous) @ angular.js:1302
invoke @ angular.js:3708
doBootstrap @ angular.js:1300
bootstrap @ angular.js:1314
(anonymous) @ loader.js:139
execCb @ require.js:1635
check @ require.js:871
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
(anonymous) @ require.js:1112
(anonymous) @ require.js:129
(anonymous) @ require.js:1155
each @ require.js:57
emit @ require.js:1154
check @ require.js:925
enable @ require.js:1142
init @ require.js:779
callGetModule @ require.js:1169
completeLoad @ require.js:1549
onScriptLoad @ require.js:1656
angular.js:9400 SyntaxError: Unexpected string in JSON at position 330749
    at JSON.parse (<anonymous>)
    at fromJson (http://localhost:9000/bower_components/angular/angular.js:1036:14)
    at defaults.defaults.transformResponse (http://localhost:9000/bower_components/angular/angular.js:6937:18)
    at http://localhost:9000/bower_components/angular/angular.js:6912:12
    at Array.forEach (native)
    at forEach (http://localhost:9000/bower_components/angular/angular.js:303:11)
    at transformData (http://localhost:9000/bower_components/angular/angular.js:6911:3)
    at transformResponse (http://localhost:9000/bower_components/angular/angular.js:7576:17)
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:10930:81)
    at http://localhost:9000/bower_components/angular/angular.js:11016:26
(anonymous) @ angular.js:9400
(anonymous) @ angular.js:6836
wrappedCallback @ angular.js:10933
(anonymous) @ angular.js:11016
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
(anonymous) @ angular.js:9400
responseError @ loading-bar.js:135
wrappedErrback @ angular.js:10939
wrappedErrback @ angular.js:10939
(anonymous) @ angular.js:11065
$eval @ angular.js:11936
$digest @ angular.js:11762
$apply @ angular.js:12042
done @ angular.js:7824
completeRequest @ angular.js:8007
xhr.onreadystatechange @ angular.js:7963
angular.js:9400 TypeError: Cannot read property 'url' of undefined
    at responseError (notificationWidget.js:143)
    at wrappedErrback (angular.js:10939)
    at angular.js:11065
    at Scope.$eval (angular.js:11936)
    at Scope.$digest (angular.js:11762)
    at Scope.$apply (angular.js:12042)
    at done (angular.js:7824)
    at completeRequest (angular.js:8007)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7963)

**Comment by Anh3h** [comment]
Hi @Ippezrobert ,
Sorry for the delayed reply I had some issues with my chrome browser.
I did run the grunt clean serve didn't get any such errors and my community app works fine.
But I can't test out the merged notification module.

**Comment by avikganguly01** [comment]
@ad-os / @gauravsaini03  : If the PR is approved, can it be merged? Corresponding platform changes are merged.

**Comment by awasum** [comment]
@Anh3h , @santoshconflux  What is the status of this PR. Will you be able to resolve conflict and resend a new one as this has already been approved and the corresponding PR merged on Fineract side.

**Comment by awasum** [comment]
@Anh3h ...Please rebase this PR to develop..or just pull from develop and lets see if we can merge this.
Is this even still valid?

**Comment by cnangeh** [comment]
@awasum I created another PR with these changes and it has been merged already so I am going to close this.

**Pull request closed without merging**
