### PR TITLE
MIFOSX-1779 - Tooltips for Loan products

### PR DESCRIPTION
**Pull request by Muciojad**
Task: https://www.google-melange.com/gci/task/view/google/gci2014/5773582953086976
Tooltips added on right side.
Right-Wrapping still irritates my eye a bit, but however is much better than standard-placement wrapping. :)
tooltip_loan

### CODE REVIEW

**Comment by gauravsaini03** [comment]
@Muciojad Can you into this PR, some chnages is made in CSS to fix the issue you are mentioning https://github.com/openMF/community-app/pull/1222/files. 

Let me know if that fixes your issue, If it fixes then use standard placement. Also, you don't need to add CSS, as its already in alex's PR so it will work for you also.

**Comment by Muciojad** [comment]
@gauravsaini03 my CSS is same as Alex's CSS.
Using "tooltip-append-to-body" is needed to fix it.
I'll update this PR in a few hours.
Thanks :+1:

**Comment by Muciojad** [comment]
Updated. :tada:  :)

**Comment by MegaAlex** [comment]
Yep, tooltip-append-to-body should do the trick without any CSS changes. :)

**Pull request merged**
