### PR TITLE
Fix #2965 Show `Joined On` field as mandatory on employee creation

### LINKED ISSUE #2965: On employee creation, "joined on" field has no sign of showing it mandatory
## Description
When creating an employee, a joined on filled has no sign of showing its mandatory

## Steps to Reproduce
Go to Admin, then Organisation, then manage employee, create employee, fill all the fields except the "joined on" field, when you submit you will get an error that the filed can not be blank

## Expected Behaviour
The field should have the sign to show that it should not be left blank

## Actual Behaviour
There is no sign to show the field is mandatory

## Settings
- Mifos X version: 18.03
- Browser used: Chrome

## Screenshots, if any
joinedon

### PR DESCRIPTION
**Pull request by m-sameer**
## Description
Add an asterisk to show **Joined On** as mandatory on create employee.
https://demo.openmf.org/newbeta/#/createemployee/

## Related issues and discussion
#2965 

## Screenshots
- Before
screenshot from 2018-11-04 22-10-03

- After
screenshot from 2018-11-04 22-02-29

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Review by ankit01ojha — COMMENTED** [review]
@m-sameer It would be good if you can just add the late validate here so that rather than the error message a simple message( as in the attached) 'required field' is shown even if the user misses the field. You can see the ```first name``` field in the code for reference and add the late validate to this field too.
screenshot from 2018-11-05 00-58-56

**Comment by m-sameer** [comment]
I am new to web apps so could you please help me with this? Which file do I have to edit?

**Comment by ShruthiRajaram** [comment]
@m-sameer in the "createemployee.html" page only refer  the firstname attribute for late-Validate and  <form-validate>.

**Comment by m-sameer** [comment]
Still didn't get that. Could you elaborate on that please?

**Comment by ankit01ojha** [comment]
@m-sameer , My previous comment was pretty elaborate, as you know we cannot give you the direct answer so, you have to work to find the solution. Just add a ```late-validate``` in the ```joined on``` field. You need to see the code for ```first name``` or ```last name``` to see where you have to add it.

**Comment by m-sameer** [comment]
@ankit01ojha Sorry for taking so long to get back to you, the demo server was down.
I have already tried adding `late-Validate` to the `joiningDate` field but it doesn't help in showing the **Required Field** warning. I have tried many ways to get the **Required Field** label but none of them is work. Finally, I have just added `late-Validate` in the **joined on** field.

**Review by ankit01ojha — APPROVED** [review]

**Comment by m-sameer** [comment]
Resolved the conflicts.

**Comment by awasum** [comment]
@ankit01ojha  is this ready to be merged?

**Comment by m-sameer** [comment]
@ankit01ojha @awasum Please merge the PR.

**Comment by santoshconflux** [comment]
@awasum , is it ready to merge? I am seeing 'Squash and Merge' button for Community app. Or I should select 'Rebase and Merge'?

**Comment by m-sameer** [comment]
Thank you!

**Pull request merged**
