### PR TITLE
Made menu icon functional

### PR DESCRIPTION
**Pull request by tanmayanand44**
## Description
The menu icon was unresponsive.I made it functional like a hovering side bar.

## Related issues and discussion
#2714 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by gkrishnan724** [comment]
@tanmayanand44 there are merge conflicts, please resolve them

**Comment by tanmayanand44** [comment]
@gkrishnan724 I will resolve soon

**Comment by tanmayanand44** [comment]
@gkrishnan724 Now review.

**Comment by tanmayanand44** [comment]
@gkrishnan724 Please review.

**Comment by gkrishnan724** [comment]
@tanmayanand44 I just had a look at your changes, but the navbar which pops up when clicked looks different and new. I would suggest clicking the button to open the existing side nav.

**Pull request closed without merging**
