### PR TITLE
bulk-import-ui-for-all-modules

### PR DESCRIPTION
**Pull request by wkk91193**
@gauravsaini03 This commit comprises of the UI for the data import tool integration. Expect the backend changes to be pulled in soon!

### CODE REVIEW

**Comment by gauravsaini03** [comment]
@mbj36 Can you please review the pull request.

**Comment by avikganguly01** [comment]
@wkk91193 : Can you resolve the conflicts and squash again?

**Comment by wkk91193** [comment]
Ready for review

**Comment by wkk91193** [comment]
@mbj36,@gauravsaini03 any update on this?

**Comment by edcable** [comment]
@mbj36 @gauravsaini03 Given that Avik has reviewed @wkk91193's work, my view is that we merge the UI changes so that @santoshmath can begin testing these on the staging instance and we can have this ready for releasing the Mifos X distribution coming after Apache Fineract 1.2

**Comment by mbj36** [comment]
@avikganguly01 Need your final view on this PR, is this ready to be merged ?

**Comment by avikganguly01** [comment]
@wkk91193 : changeOffice, changeStaff and upload is mostly duplicate code across all controllers which can be converted to directives. 

@mbj36 : I will remove the duplicate code in a separate PR. Rest all looks good. Can you pull this in?

**Comment by mbj36** [comment]
Done @avikganguly01

**Pull request merged**
