### PR TITLE
fix #2736-Non-Uniformity of Clients,Groups,Centers list

### LINKED ISSUE #2736: Non-Uniformity of Clients,Groups,Centers list
## Description
The three sections under Clients have tables, however the formatting is not uniform.

## Steps to Reproduce
Make the layout of the 3 sub sections uniform by separation of rows. In short making Groups and Centers subsections same as that of Clients, as there in the screenshots below.
## Actual Behaviour
Non Uniformity in the layout of the tables

## Settings
- Mifos X version: 
- Browser used:

## Screenshots, if any
screenshot from 2018-01-06 04-32-16
screenshot from 2018-01-06 04-32-22
screenshot from 2018-01-06 04-32-37

### PR DESCRIPTION
**Pull request by zapdoss**
## Description
The three sections under Clients have tables, however the formatting was not uniform. Thus i made the layout of the tables uniform for all the three sections.

## Related issues and discussion
#2736 

## Screenshots, if any
screenshot from 2018-01-07 05-35-57
screenshot from 2018-01-07 05-35-53
screenshot from 2018-01-07 05-35-48

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [*] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [*] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [*] If you have multiple commits please combine them into one commit by squashing them.

- [*] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by mbj36** [comment]
Thanks for the PR, It will be reviewed Shortly!

(Powered by [GitMate.io](https://gitmate.io))

**Comment by edcable** [comment]
@abhi40308 if the change here is only as simple as renaming the commit message are you able to do that and merge?

**Comment by abhi40308** [comment]
@edcable remote is deleted from which the pr was sent, due to which I can't checkout. Should I raise new pr picking the changes?

**Comment by spider0061** [comment]
Closing! The contributor seems to be inactive.

**Pull request closed without merging**
