### PR TITLE
Fixed issue #1753 and adjusted alignments of top 2 rows

### PR DESCRIPTION
**Pull request by Anh3h**

### CODE REVIEW

**Comment by mbj36** [comment]
@Anh3h should i close this one https://github.com/openMF/community-app/pull/1925 ?

**Comment by Anh3h** [comment]
Yeah since this one has the updated code of that one plus the new alignment adjustment you sudjested

**Comment by Anh3h** [comment]
I will continue with the other reskin issues. If you need an issue to fixed ASAP am your girl.

**Comment by mbj36** [comment]
Thanks @Anh3h This PR looks perfect

**Pull request merged**
